platypusguy/jacobin

src/log/logger.go
src/main.go

FWIW, Log mutex amendment

---

src/classloader/classloader.go

Cleaning up some error messages

---

src/classloader/classloader.go
src/jvm/run.go
src/jvm/run_test.go

- Implemented most floating point operations (array and compare ones TBD).
- Updated missing bytecode messaging
- Improved classloader resolution

Floating point operations

---

src/jvm/run.go

Go through param types in reverse order

---

.github/workflows/go.yml

Just the workflow change: go.yml

Build and test on ubuntu, windows, and macos

---

.github/workflows/go.yml

There may be other files that should be excluded in the future.

No need for github actions on an .md file update

---

src/jvm/run.go

See https://jacobin.myjetbrains.com/youtrack/issue/JACOBIN-249

added tracing to run.go, fixed JACOBIN-252

---

src/classloader/classloader.go
src/classloader/jmod.go
src/classloader/jmodMap.go
src/classloader/jmodMap_test.go
src/globals/globals_test.go
test_one/jmodMap.bat
test_one/jmodMap.sh

Modifications:
new file:   src/classloader/jmodMap.go
new file:   src/classloader/jmodMap_test.go
new file:   test_one/jmodMap.bat
new file:   test_one/jmodMap.sh
deleted:    src/classloader/cjmap.go
deleted:    src/classloader/cjmap_test.go
modified:   src/classloader/classloader.go
modified:   src/classloader/jmod.go
modified:   src/classloader/jmodMap_test.go
modified:   src/globals/globals_test.go <-------------------- foo/bar
deleted:    test_one/cjmap.bat
deleted:    test_one/cjmap.sh

cjmap -> jmodMap, test fixups

---

src/classloader/classloader.go
src/classloader/hexClass.class_test.go
src/classloader/methArea.go
src/jvm/instantiate.go

except for StrictMath which I am tracking down.

LoadClassByNameOnly is working

---

src/classloader/classes.go
src/classloader/classloader.go
src/jvm/run.go

Fixed:
* classloader.go
* classes.go
* run.go

JACOBIN-287 Guard against blank class name from INSTANCEOF+CHECKCAST

---

src/classloader/classes.go
src/jvm/run.go
src/shutdown/exit.go

When we cannot find a class or method, there is no point in going on.

JACOBIN-303 Add more shutdowns in FetchMethodAndCP

---

src/jvm/run.go

When tracing, this might add more visibility.
Tracing:
* argument for push
* TOS entry for peek
* result for pop

push/pop/peek trace value+type

---

src/classloader/javaLangMath.go
src/classloader/mTable.go
src/jvm/goFunctionExec.go

Math.x and StrictMath.x are implemented as Go methods.
Files affected:
* New - javaLangMath.go
* Modified - mTable.go
TODO: Define E and PI as Math class attribute fields.
TODO: Unit tests.

JACOBIN-309 New: javaLangMath.go

---

src/classloader/javaLangMath.go

The jacobin unit tests work fine.

Miscellaneous fixes for Math & Strict Math

---

src/classloader/javaLangMath.go

Hopefully, that is that!
(Probably, not)
TODO: Update jacotest.go right now. <--- done

Fixed Math.ulp

---

src/classloader/javaLangMath.go
src/jvm/run.go

* Minor fixes to cover some boundary conditions.
* More consistent use of argument names - hopefully easier to read and search in the future.
* Did not implement some boundary checks for passthrough to native Go functions, for better and/or worse.
* Did not implement some boundary checks for some hand-coded functions, for better and/or worse.
This would be a great time to get an intern / teaching assistant to be the disinterested 3rd party tester! Dream on, eh? (:
Its time to move on. Maybe, the file system for some basic I/O to disk files and directories.
Or, tackle the list of test case failures - at least, analysis.

Minor Math/StrictMath edits (last for now)

---

src/jvm/instantiate.go

* Correct identification of function in error messages.
* Shutdown instead of returning an error when class readiness times out.
Note that the current issue of ```class.Data is nil``` is not yet solved.

minor edits in loadThisClass

---

src/jvm/run.go

Fix to tracing situations when obj.Fields is an empty array

JACOBIN-331 tracing mishaps run.go

---

.github/workflows/go.yml
src/globals/globals.go
src/go.mod

Files affected:
* .github/workflows/go.yml
* src/go.mod

Adopt go 1.21 JACOBIN-330

---

src/classloader/formatCheck.go

Fix typo in formatCheck.go

---

src/jvm/goFunctionExec.go

Just what it says!
And trace G frame too.

JACOBIN-388 : trace G method class, method name, and method type

---

src/classloader/javaIoPrintStream.go
src/classloader/javaLangString.go

This PR covers 2 topics:
- Create a StringFormatter function to handle the formatting aspects of
- printf
- String.format(formatString, prtObjectSlice)
- formatString.formatted(prtObjectSlice)
- Using an ellipsis for the params interface array in processing the individual prtObjects.

JACOBIN-393 : Centralise formatting slices of objects

---

src/classloader/javaLangString.go
src/jvm/goFunctionExec.go
src/jvm/run.go
src/object/object.go

- Align trace output.
- Show values of fields where we can.
- Flag nil Klass pointers, nil field pointers, and objects that have no fields at all.
- Show class, method name, and method type as a single concatenated string.
- Added String.length() as a new G function.

JACOBIN-397 First effort at trace normalisation, String.length(), minor corrections

---

src/classloader/javaIoPrintStream.go
src/classloader/javaLangString.go
src/jvm/run.go
src/object/object.go

File affected: javaLangString.go

Add String.compareTo and compareToIgnoreCase

---

src/gfunction/javaLangThrowable.go
src/globals/globals.go
src/jvm/instantiate.go
src/jvm/instantiate_test.go
src/jvm/jvmStart.go
src/jvm/run.go

The Cycle: InstantiateClass (jvm) >> ... >> fillInStackTrace (gfunction) >> InstantiateClass
Solution: See JACOBIN-410.

JACOBIN-410 End the jvm cycle

---

src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangString.go
src/gfunction/javaLangSystem.go
src/gfunction/javaPrimitives.go
src/gfunction/javaUtilHashMap.go
src/gfunction/javaUtilLocale.go

Includes the javaPrimitives.go.

gfunction migration except throw

---

src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangString.go

fix formatting for single character

---

src/gfunction/javaLangString.go

New byte[]-to-String conversion strategy:
Copy the whole  (```newStringFromBytes```) or subset (```newStringFromBytesSubset```) byte array from the user's supplied parameter (a byte array) to the implicit String object's byte array.
params[0] : implicit String object used as output
params[1] : user supplied byte array in an object

JACOBIN-422 fix to running out of stack in a small loop

---

src/object/String.go
src/object/String_new-ish_test.go
src/statics/statics.go

Files impacted:
* modified:   object/String.go
* modified:   statics/statics.go (no functional changes, just alphabetized load list)
* new file:   object/String_new-ish_test.go

JACOBIN-463 New string primitives

---

src/gfunction/javaLangThrowable_test.go
src/gfunction/javaUtilLocale.go

modified:   ```gfunction/javaLangThrowable_test.go```
modified:   ```gfunction/javaUtilLocale.go```
but not yet for ```javaLangString.go```

JACOBIN-463 using MakeEmptyObjectWithClassName

---

src/gfunction/javaLangString.go
src/gfunction/javaLangString_test.go
src/globals/globals.go
src/object/String.go
src/stringPool/StringPool.go
src/stringPool/StringPoolPrimitives_test.go

modified:   gfunction/javaLangString_test.go
modified:   globals/globals.go
modified:   object/String.go
modified:   stringPool/StringPool.go
modified:   stringPool/StringPoolPrimitives_test.go
Not all unit tests pass:
[oops.log](https://github.com/platypusguy/jacobin/files/14551048/oops.log)
I have a specific question about ```TestStringClinit```. Why is this happening?
```javaLangString_test.go:29: TestStringClinit: Unexpected error message. got stringClinit: Could not find class java/lang/String in the MethodArea```

javaLangString + fixes

---

src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangString_test.go

fixed PrintString and PrintlnString

---

src/gfunction/javaLangInteger.go
src/gfunction/javaLangString.go
src/object/String.go

Mostly, work in gfunction/javaLangInteger.go.
Jacotest 3.1.3 added a new test case that covers every function in javaLangInteger.go.

JACOBIN-477 expand java.lang.Integer and java.lang.String gfunctions

---

src/gfunction/javaUtilLocale.go

JACOBIN-480 fixed getDefaultLocale to use new string API

---

src/jvm/run.go

run.go IF* cases are affected.
I created a generic xlateIfArg function that accepts an interface{} argument and returns an int64 value.

JACOBIN-483 Opcodes IF* and IF_* can receive uint8 values as well as int64 values

---

src/jvm/run.go

Modified case TABLESWITCH in run.go

JACOBIN-484 TABLESWITCH completed, I believe

---

.github/workflows/go.yml
src/exceptions/exception.go
src/exceptions/exception_test.go
src/gfunction/Traps.go
src/gfunction/gfunction.go
src/gfunction/javaIoBufferedReader.go
src/gfunction/javaIoFile.go
src/gfunction/javaIoFileInputStream.go
src/gfunction/javaIoFileReader.go
src/gfunction/javaIoInputStreamReader.go
src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangString.go
src/gfunction/javaNioCharsetCharset.go
src/types/javaTypes.go

* New test file, exception_test.go, to make sure that the exception numerical list and the string list are in alignment.
* Minimal java/nio/charset/Charset stuff: justReturn <clinit> and a trap for defaultCharset.

JACOBIN-493 File I/O MegaPR (file input only)

---

src/gfunction/Traps.go
src/gfunction/gfunction.go
src/gfunction/javaIoFileInputStream.go
src/gfunction/javaIoFileOutputStream.go
src/jvm/run.go

modified:   gfunction/gfunction.go - Load javaIoFileOutputStream.go table
modified:   gfunction/javaIoFileInputStream.go - make messages more consistent
added:        gfunction/javaIoFileOutputStream.go - new functions
modified:   jvm/run.go - When op code is not yet supported, show method type as well as method name.

JACOBIN-493  javaIoFileOutputStream.go

---

src/gfunction/Traps.go
src/gfunction/javaIoFile.go
src/gfunction/javaLangThread.go

Added:
* File.createNewFile
* File.delete
* Thread.Sleep
* a trap for javaIoFileSystem.<clinit>

JACOBIN-493 Minor changes to Traps.go, javaIoFile.go, and javaLangThread.go

---

src/gfunction/Traps.go
src/gfunction/gfunction.go
src/gfunction/javaUtilRandom.go
src/globals/globals.go

Exceptions:
* The stream output (E.g. IntStream) has no coverage.
* Trapped: protected int next(int bits).  Source code: "This method should never be reached unless done by reflection so we should throw when tried".

JACOBIN-502 work on native functions for java/util/Random

---

src/exceptions/throw.go
src/jvm/run.go
src/jvm/runUtils.go

* Commented out DEBUG Printf in methodParser.go
* run.go INVOKEINTERFACE should expect `classloader.Interface`, not `classloader.MethodRef`
* runUtils.go::traceObject corrections

JACOBIN-506 expand tracing, update to INVOKEINTERFACE 

---

src/gfunction/Traps.go
src/gfunction/javaIoBufferedReader.go
src/gfunction/javaIoConsole.go
src/gfunction/javaIoFile.go
src/gfunction/javaIoFileInputStream.go
src/gfunction/javaIoFileOutputStream.go
src/gfunction/javaIoFileReader.go
src/gfunction/javaIoInputStreamReader.go
src/gfunction/javaIoOutputStreamWriter.go
src/gfunction/javaLangByte.go
src/gfunction/javaLangClass.go
src/gfunction/javaLangDouble.go
src/gfunction/javaLangInteger.go
src/gfunction/javaLangString.go
src/gfunction/javaLangSystem.go
src/gfunction/javaLangThrowable.go
src/gfunction/javaLangThrowable_test.go
src/gfunction/javaUtilRandom.go
src/gfunction/jdkInternalMiscUnsafe.go

Modified source files:
* gfunction/Traps.go
* gfunction/javaIoBufferedReader.go
* gfunction/javaIoConsole.go
* gfunction/javaIoFile.go
* gfunction/javaIoFileInputStream.go
* gfunction/javaIoFileOutputStream.go
* gfunction/javaIoFileReader.go
* gfunction/javaIoInputStreamReader.go
* gfunction/javaIoOutputStreamWriter.go
* gfunction/javaLangByte.go
* gfunction/javaLangClass.go
* gfunction/javaLangDouble.go
* gfunction/javaLangInteger.go
* gfunction/javaLangString.go
* gfunction/javaLangSystem.go
* gfunction/javaLangThrowable.go
* gfunction/javaLangThrowable_test.go
* gfunction/javaUtilRandom.go
* gfunction/jdkInternalMiscUnsafe.go

JACOBIN-515 All G function error messages should follow a common pattern

---

src/gfunction/gfunction.go
src/gfunction/javaLangBigInteger.go
src/gfunction/javaMathBigInteger.go
src/gfunction/justReturn.go
src/jvm/run.go

JACOBIN-516 When GETFIELD detects an invalid object type, name the field.
JACOBIN-517 Implement BigInteger.valueOf(). More of these upcoming. See commits below.

JACOBIN-516 JACOBIN-517 Dual Purpose

---

src/gfunction/javaMathBigInteger.go

See
https://jacobin.myjetbrains.com/youtrack/issue/JACOBIN-530/Correct-BigInteger-calculations-add-init-with-Random

JACOBIN-530: Correct BigInteger calculations; add init with Random

---

src/gfunction/Traps.go
src/gfunction/gfunction.go
src/gfunction/javaMathBigInteger.go
src/gfunction/javaSecuritySecureRandom.go

Impacted source code:
* gfunction/Traps.go - remove traps for SecureRandom
* gfunction/gfunction.go - added Load_Security_SecureRandom
* gfunction/javaMathBigInteger.go - use SecureRandom
* gfunction/javaSecuritySecureRandom.go - new, mostly dummy

JACOBIN-530 Use SecureRamdom object with BigInteger

---

src/gfunction/Traps.go
src/gfunction/gfunction.go
src/gfunction/javaLangString.go
src/gfunction/javaLangStringBuilder.go
src/gfunction/justReturn.go

modified:   gfunction/Traps.go
modified:   gfunction/javaLangStringBuilder.go
modified:   gfunction/justReturn.go
The individual commit messages contain the descriptions.

JACOBIN-538 gfunction maintenance

---

src/jvm/run.go

JACOBIN-542 INVOKESPECIAL & INVOKEVIRTUAL

---

src/gfunction/javaIoFile.go

See YouTrack JACOBIN-546.
File affected: gfunction/javaIoFile.go

JACOBIN-546 Insert warn-level logging in the os.Remove & os.Create failure cases

---

src/gfunction/javaLangString.go
src/gfunction/javaLangString_test.go
src/jvm/run.go

Impacted:
* gfunction/javaLangString.go
* jvm/run.go

JACOBIN-547 String improvements

---

src/exceptions/catchFrame.go

Modifications:
* exceptions/catchFrame.go (JACOBIN-559)
* gfunction/javaIoInputStreamReader.go - move failure on to the correct symptom: encoding

JACOBIN-559 Eliminate throws from within exception handling

---

src/gfunction/javaIoFile.go
src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangSystem.go
src/jvm/arrayBytecodes_test.go
src/jvm/run.go
src/object/string.go
src/object/toString_test.go

Please see JACOBIN-501 for a description.
Affected source files:
* jvm/arrayBytecodes_test.go
* jvm/run.go

JACOBIN-501 run.go BASTORE + array unit tests

---

src/gfunction/javaIoRandomAccessFile.go
src/gfunction/javaLangSystem.go

modified:   gfunction/javaIoRandomAccessFile.go
modified:   gfunction/javaLangSystem.go

JACOBIN-560 move jacotest case fits along to needing statics loaded by class Properties

---

src/gfunction/javaLangStringBuffer.go
src/gfunction/javaLangStringBuilder.go
src/gfunction/justReturn.go

Updated source files:
- gfunction/javaLangStringBuffer.go
- gfunction/javaLangStringBuilder.go

JACOBIN-547 StringBuilder & StringBuffer replace and reverse

---

src/gfunction/Traps.go

Its a simple update to src/gfunction/Traps.go

Stop double-trapping Charset

---

src/gfunction/gfunctionExec.go
src/gfunction/javaLangInteger.go
src/gfunction/javaLangString.go
src/jvm/gfunctionExec_test.go
src/jvm/initializerBlock.go
src/jvm/run.go
src/jvm/runUtils.go

JACOBIN-578 String startsWith
JACOBIN-579 move gfunctionExec.go from the jvm package to the gfunction package

JACOBIN-578 +  JACOBIN-579 

---

src/go.mod
src/go.sum
src/native/nativeBase.go
src/native/nativeFuncExec.go

See earlier email on this subject.

JACOBIN-582 added native table defs and getFuncHandle()

---

src/gfunction/gfunction.go
src/gfunction/javaUtilZipAdler32.go
src/gfunction/javaUtilZipCrc32.go

new file:   gfunction/javaUtilZipAdler32.go
new file:   gfunction/javaUtilZipCrc32.go

JACOBIN-589 Implement Java CRC functions as G functions

---

src/jvm/cli.go
src/jvm/cli_test.go
src/jvm/option_table_loader.go

@platypusguy  
See today's email.
modified:   jvm/cli_test.go
modified:   jvm/option_table_loader.go

JACOBIN-498 use comma(,) as a -trace separator

---

src/jvm/run.go
src/jvm/runUtils.go

Modified in package jvm:
* run.go
* runUtils.go

JACOBIN-498 adapt run.go, runUtils.go to use -trace as intended

---

src/gfunction/javaMathBigInteger.go

modified:   gfunction/javaMathBigInteger.go

 JACOBIN-592 JACOBIN-592 fix bigIntegerValueOf argument index

---

src/gfunction/javaUtilHexFormat.go
src/object/object.go

Still need to fix HexFormat.equals() but included here seems to be a valid CloneObject.
Morgan, Henry.

JACOBIN-614 CloneObject

---

src/gfunction/jj.go

Modified: gfunction/jj.go
Supports jacotest ability to fetch a single static field or a single object field.

JACOBIN-626 added ability to get/stringify one static and one object field

---

src/gfunction/jj.go
src/statics/statics.go

modified:   gfunction/jj.go
modified:   statics/statics.go

JACOBIN-627 jj.go arrays/slices for statics and obj fields

---

src/gfunction/gfunction.go
src/gfunction/javaSecuritySecureRandom.go
src/gfunction/javaUtilConcurrentAtomicAtomicInteger.go
src/jvm/interpreter.go

* No more timeouts. Protecting against nil code segments (abstract) (JACOBIN-633).
* More implementation of SecureRandom; fixes to AtomicInteger (JACOBIN-633).
modified:   gfunction/javaSecuritySecureRandom.go
modified:   gfunction/javaUtilConcurrentAtomicAtomicInteger.go
modified:   jvm/interpreter.go

JACOBIN-633 (protection against closed loop only), JACOBIN-635

---

src/gfunction/Traps.go
src/gfunction/gfunction.go
src/gfunction/javaUtilConcurrentAtomicAtomicInteger.go

modified:   gfunction/Traps.go
modified:   gfunction/javaUtilConcurrentAtomicAtomicInteger.go

JACOBIN-638 fixes and additions to AtomicInteger

---

src/gfunction/Traps.go
src/gfunction/javaLangInteger.go

src/gfunction/Traps.go - Trap ByteArray{Input,Output}Stream <clinit>.
src/gfunction/javaLangInteger.go - Decode hex format correctly.

JACOBIN-641 & JACOBIN-644

---

src/gfunction/Traps.go
src/gfunction/javaSecuritySecureRandom.go
src/object/string.go
src/types/javaTypes.go

modified:   gfunction/Traps.go: added trapProtected
modified:   gfunction/javaSecuritySecureRandom.go: math/rand ---> crypto/rand (secure)
modified:   object/string.go - remove reference to RNG
modified:   types/javaTypes.go - remove reference to RNG

JACOBIN-673 math/rand ---> crypto/rand (secure)

---

src/gfunction/javaLangClass.go
src/gfunction/javaLangSystem.go

- gfunction/javaLangSystem.go: JACOBIN-694 getenv
- gfunction/javaLangClass.go: JACOBIN-695 isArray

Contributions towards: JACOBIN-692  Implement the needed gfunctions to make Jacotests pass

---

src/gfunction/gfunction.go
src/gfunction/javaUtilHashMap.go
src/types/javaTypes.go

modified:   gfunction/gfunction.go - load the MethodSignature entries.
modified:   types/javaTypes.go - ftype=HM
new file:   gfunction/javaUtilHashMap.go - <init>, put, get, etc.

JACOBIN-696 HashMap

---

src/classloader/codeCheck.go

modified:   classloader/codeCheck.go
See email of this morning.

fix for checkGetfield

---

src/gfunction/gfunction.go
src/gfunction/javaIoBufferedReader.go
src/gfunction/javaUtilBase64.go
src/gfunction/javaUtilHashMap.go
src/gfunction/jj_test.go
src/object/object.go

- new file:   gfunction/javaUtilBase64.go - Base64 functions
- modified:   gfunction/gfunction.go - load Base64 functions
- modified:   gfunction/javaIoBufferedReader.go - minor edit
- modified:   object/object.go - new function: MakeOneFieldObject. Similar to MakePrimitiveObject except this one accepts the field name as a parameter. 
- modified: gfunction/jj_test.go - JACOBIN-689 use AddStatic

JACOBIN-697 Base64

---

src/jvm/interpreter.go
src/object/arrays.go

modified:   jvm/interpreter.go
modified:   object/arrays.go

JACOBIN-703 GETFIELD and object.ArrayLength

---

src/jvm/interpreter.go

JACOBIN-712 Make sure the user message is visible in AssertionError

---

src/gfunction/gfunction.go
src/gfunction/javaLangProcessHandleImpl.go
src/gfunction/javaUtilObjects.go
src/gfunction/javaUtilOptional.go
src/object/string.go

new file:   gfunction/javaUtilOptional.go : new
modified:   gfunction/gfunction.go : load the method signature tables
modified:   gfunction/javaLangProcessHandleImpl.go : edits, new functions
modified:   gfunction/javaUtilObjects.go : deleted erroneous comment
modified:   object/string.go : new function, StringObjectArrayFromGoStringArray

JACOBIN-715 java/lang/ProcessHandle, java/lang/ProcessHandle.Info, java/util/Optional

---

src/gfunction/javaMathBigInteger.go
src/gfunction/javaUtilOptional.go

BigInteger additions: left shift, right shift, test bit, and set bit

BigInteger just got bigger!

---

src/gfunction/javaIoPrintStream.go
src/gfunction/jj.go

JACOBIN-718 handle int8 or int64 as int64

---

src/gfunction/gfunction.go
src/gfunction/javaLangThrowable.go
src/gfunction/javaUtilLinkedList.go
src/gfunction/javaUtilLinkedListFuncAtoQ.go
src/gfunction/javaUtilLinkedListFuncRtoZ.go
src/object/string.go
src/types/javaTypes.go

new file:   gfunction/javaUtilLinkedList.go
new file:   gfunction/javaUtilLinkedListFuncAtoQ.go
new file:   gfunction/javaUtilLinkedListFuncRtoZ.go
modified:   gfunction/gfunction.go - Load_Util_LinkedList().
modified:   gfunction/javaLangThrowable.go - Missing semicolons in Lclass specifications. Cosmetic? Probably.
modified:   object/string.go - New function: EqualStringObjects: Compare two string objects for equality.
modified:   types/javaTypes.go - types.LinkedList

JACOBIN-722 LinkedList

---

src/gfunction/Traps.go
src/gfunction/gfunction.go
src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangClass.go
src/gfunction/javaLangDouble.go
src/gfunction/javaUtilLinkedList.go
src/gfunction/javaUtilLinkedListFuncRtoZ.go
src/types/constants.go

LinkedList.toArray (2 flavours)
* javaUtilLinkedListFuncRtoZ.go
Filled out Double:
* gfunction/javaLangDouble.go
* gfunction/gfunction.go
Class.getModule() - unnamed - move some test cases along (onion peeling):
* gfunction/javaLangClass.go 
* types/constants.go
Confess rather than chaos:
* src/gfunction/Traps.go

JACOBIN-722 2 flavors of LinkedList toArray() and more

---

src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangFloat.go
src/gfunction/javaLangSystem.go
src/gfunction/javaLangSystem_test.go

gfunction/javaIoPrintStream.go - fixed `_printString()`.
gfunction/javaLangFloat.go - rewrite in collaboration with chatGPT.

JACOBIN-692 fill out class Float, JACOBIN-725 GA Ubuntu panic resolution

---

src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangObject.go
src/gfunction/javaMathBigInteger.go
src/gfunction/javaUtilLinkedList.go
src/gfunction/javaUtilLinkedListFuncRtoZ.go
src/object/object.go
src/object/string.go
src/object/stringifyAnything.go

new file:   object/stringifyAnything.go
modified:   gfunction/javaIoPrintStream.go - make use of object.StringifyAnythingGo().
modified:   object/object.go - new function GetClassNameSuffix().
modified:   object/string.go - ObjectFieldToString
* Protect against nil/null objects.
* Recognise Field.Ftype = types.StringClassRef

JACOBIN-727 Improve object and LinkedList printing

---

src/gfunction/gfunction.go
src/gfunction/javaLangProcess.go
src/gfunction/javaLangProcessBuilder.go
src/gfunction/jj.go
src/object/string.go

new file:   gfunction/javaLangProcessBuilder.go - traps
modified:   gfunction/gfunction.go - enable Load_Lang_Process(), Load_Lang_Process_Builder()
modified:   gfunction/javaLangProcess.go - traps
modified:   gfunction/jj.go - new function, jjSubProcess
modified:   object/string.go - new function, GoStringArrayFromStringObjectArray

JACOBIN-748 Support jacotest cases that need to sub-process

---

src/jvm/interpreter.go

interpreter.go, funcDoAthrow, line 2927

JACOBIN-751 assert 1==0 should just fail w/o crashing

---

src/classloader/cpResolution.go

modified: classloader/cpResolution.go

JACOBIN-754 Voluminous "Resolved ....." stderr messages

---

src/gfunction/Traps.go
src/gfunction/gfunction.go
src/gfunction/javaLangString.go
src/gfunction/javaLangSystem.go
src/gfunction/javaLangSystem_test.go
src/gfunction/jdkInternalMiscUnsafe.go
src/gfunction/otherMethods.go
src/gfunction/sunSecurityActionGetPropertyAction.go

See documentation in JACOBIN-770.

JACOBIN-770 miscellaneous changes
