src/classloader/cpParser_test.go

This PR is based on my creating a temporary repo and testing uncommenting out the lines referenced in issue #1.
Either I have the magic touch [(-;] or Unka Andoo's activity last night somehow cleansed something (?).

Uncomment lines from issue #1

---

.github/workflows/go.yml

One file affected: ```jacobin/.github/workflows/.go.yml```

JACOBIN-221: Run testing without the -short option

---

AUTHORS.txt
src/jvm/run.go

Push and pop have been amended per the JACOBIN-247 discussion. As it turns out, peek was fine the way it was.
Sample trace from test case JACOBIN-0212-bit-shifting:
[trace.txt](https://github.com/platypusguy/jacobin/files/11442052/trace.txt)

Amended tracing to be after push/pop effects

---

src/classloader/classloader.go
src/classloader/jmod.go
src/classloader/methArea.go
src/globals/globals.go
src/globals/globals_test.go
src/jvm/cli.go
src/jvm/instantiate.go
src/jvm/jvmStart.go

@platypusguy 
This is an initial PR. You can merge it any time. If still open, I will add to it. Otherwise, I'll open a new PR.
This list will continue to be updated.
* Added shutdowns in classloader.go LoadBaseClasses error situations.
* Added and amended commentary in a few places classloader.go - some based on discussion in JACOBIN-268.
* Updated some URLs to point to the Java/JVM version 17 documentation.
* Removed reference to JacobinHome from LoadClassByNameOnly (to be extensively revamped). As it turns out, this change was not necessary at this time. Jacobin home directory concept is still under discussion.
* In LoadClassByNameOnly, logging with accompanying context was added at the points of error recognition.
* Add the name of the function in several error messages so to see …

Classloader cleanup +getting ready for the Big Bang

---

.github/workflows/go.yml
.gitignore
src/classloader/cjmap.go
src/classloader/cjmap_test.go
src/classloader/classloader.go
src/globals/globals.go
test_one/cjmap.bat
test_one/cjmap.sh

This could be a multi-step PR. It can be merged at any time after review.
In the first push, cjmap.go is now functional and exercised by cjmap_test.go. But, cjmap.go is not yet invoked during jacobin initialisation.

New classloader source: cjmap.go & cjmap_test.go

---

src/classloader/classes.go
src/classloader/classloader.go
src/classloader/getClassBytes.go
src/classloader/jmodMap.go
src/classloader/jmodMap_test.go
src/classloader/methArea.go
src/globals/globals.go
src/globals/globals_test.go
src/jvm/instantiate.go
src/jvm/run.go
test_one/jmodMap.sh

This PR addresses JACOBIN-266 and JACOBIN-270.
**Source changes**
new file:   src/classloader/getClassBytes.go
modified:   src/classloader/classes.go
modified:   src/classloader/classloader.go
modified:   src/classloader/jmodMap.go
modified:   src/classloader/jmodMap_test.go
modified:   src/classloader/methArea.go
modified:   src/globals/globals.go
modified:   src/globals/globals_test.go
modified:   src/jvm/instantiate.go
modified:   src/jvm/run.go
modified:   test_one/jmodMap.sh
**Last jacotest session failure report**
```
Failed Test Case Summary - 2023-06-10 17:34:51 CDT
===========================
panic: interface conversion
===========================
FAILED.JACOBIN-0211-pbcrypto.jacobin.log: panic: interface conversion: interface {} is *[]int8, not *object.Object …
```

jacobin v0.3.1 started

---

src/classloader/TestLoadClass_test.go
src/classloader/classes.go
src/classloader/classloader.go
src/classloader/jmodMap_test.go

JACOBIN-270
JACOBIN-271
It wasn't just StrictMath. It was any INVOKESTATIC situation that required loading a not previously loaded class.
FetchMethodAndCP now calls LoadClassFromNameOnly(classname) to make sure that the class is loaded if need be.
AND FetchMethodAndCP **ONLY** calls LoadClassFromNameOnly when MethAreaFetch says the class aint loaded!

Solved StrictMath anomaly in FetchMethodAndCP

---

src/jvm/run.go

E.g. in jacotest case JACOBIN-0217-multidim-3d,
```
AASTORE: field type expected=[L, observed=[I
AASTORE: Attempt to access array of incorrect type
```

Provide failure evidence for xxSTORE cases of run.go

---

src/jvm/run.go

INSTANCEOF is currently producing a ""-valued className as input to classloader. 
One line fix to run.go.

JACOBIN-287 fix class name retrieval in INSTANCEOF processing (PR #46 from texadactyl/main)

---

src/jvm/run.go

Summary:
- Important: Do not allocate the Locals until one know how many arguments will be inserted. Cannot rely on m.MaxLocals alone.
- Initial allocation size = maximum of m.MaxLocals and len(argList) but must also be at least 1.
- If includeOjectRef is true (coming from invokevirtual, invokespecial, or invokeinterface), then make room for one more and pop into Locals[0].
- Then, load the arguments in reverse order into the remaining Locals.

JACOBIN-304 - Fix for createAndInitNewFrame

---

src/jvm/run.go

I changed createAndInitNewFrame:
* Pop off the objectref LAST per original version. Add supporting code to make room for the objectref in the frame Locals array.
* For more information in tracing, added the string values of the class name, method name, and method type.
* When m.MaxStack = 0, what do we do instead of this:
```fram := frames.CreateFrame(m.MaxStack)```
Included in this PR:
```
stackSize := m.MaxStack
if stackSize < 1 {
stackSize = 1
}
fram := frames.CreateFrame(stackSize)
```
Need to know: Are INVOKEVIRTUAL and INVOKESPECIAL supposed to push the object reference or was a prior opcode step supposed to push the object reference?
Answer: A prior opcode is supposed to do it. No additional pushes should be required from INVOKEVIRTUAL and INVOKESPECIAL.
This still remains The Case …

JACOBIN-305 createAndInitNewFrame must pop objectref BEFORE the parameters

---

src/classloader/javaLangSystem.go

Defined the following system properties:
* java.class.path = "." just like OpenJDK JVM when CLASSPATH is not defined. TBUed when the CLASSPATH work ensues.
* line.separator = "\n" for POSIX and "\r\n" for Windows.
* os.version is not provided directly in go so "not yet available" for the moment.
If Go provides a runtime GOOS and GOARCH, why not provide a GOOSVER? It can be as simple as the distro version like "11" for Windows or "22.04" in Ubuntu. Anyways, if we give up waiting for the Go Gods in the future, we can provide os.version ourselves using different ways of getting it with low-level functions.

provide missing system properties

---

src/classloader/classes.go
src/jvm/run.go

INVOKEVIRTUAL must emit the error message when a class method is not found because classloader.FetchMethodAndCP does not log when a method is not found; it simply returns error text to be used by caller.

JACOBIN-354

---

src/classloader/javaIoPrintStream.go
src/classloader/javaLangMath.go
src/jvm/run.go

1. Ensure to capture the golang-stack immediately after entering the deferred recover function (JACOBIN-367).
2. Add a ```<clinit>``` function to java LangMath.go (JACOBIN-368).
3. Add boolean support to javaIoPrintStream.go (JACOBIN-370).

JACOBIN-367 and JACOBIN-368 and JACOBIN-370

---

src/jvm/run.go

* Capture stack in op-code error sections of run.go
* When logging an error, msg --> errMsg
* When logging a trace, msg --> traceInfo
* Work towards JACOBIN-373
* Added ```logTraceStack(f)``` to PUTFIELD when there is an error. Sufficient, @platypusguy ?
* Added ```logTraceStack(f)``` to the end of funcs pop, peek, and push to show the resultant stack.
* In run.go, make sure that ```return errors.New(errMsg)``` is used everywhere instead of returning ```fmt.Errorf()``` in a few places (inconsistent). 
**Read the following before reviewing.**
I backed out 2 experiments from this PR:
* func pop: added an immediate return of nil on an empty stack input - clearly wrong.
* ARETURN: diagnosed the result of a pop which produced a nil reference. Does not seem to be valid. @platypusguy ? 
**Stack …

JACOBIN-374 and work towards JACOBIN-373

---

src/classloader/javaLangMath.go
src/classloader/javaLangString.go
src/classloader/javaLangSystem.go

The ```<clinit>``` routine was expecting the class to be already loaded in the method area but it wasn't.
Source files affected in package classloader:
- javaLangMath.go
- javaLangString.go
- javaLangSystem.go

Throw exception when <clinit> diagnoses an unrecoverable error

---

src/classloader/javaLangString.go
src/exceptions/exception.go

This covers the cases:
* getBytes(string)
* getBytes(Charset)

Trap user-specified Charset in String.getBytes(...)

---

src/thread/jvmThread.go
src/thread/jvmThread_test.go

See discussion in JACOBIN-385.
Also, see email about Golang channel vs WaitGroup. What I changed (removing channel) may not matter but the channel and waiting in a thread was not necessary, IMO.
BUT all that was needed: fix ```incrementThreadNumber``` - see below.

JACOBIN-385: timing issue in jvmThread.go incrementThreadNumber

---

src/classloader/javaLangString.go
src/jvm/run.go

* **classloader/javaLangString.go**
- Fixed some entries that specified 0 arguments (lied) even though these entries result in an exception today (maybe not tomorrow).
- Added entries for 
- ```java/lang/String.<init>([BLjava/lang/String;)V```
- ```java/lang/String.<init>([BLjava/nio/charset/Charset;)V```
* **jvm/run.go** - fixed INVOKESPECIAL to pass only the method name in the ```methName``` parameter in the call to ```runGmethod```. The former code broke ```java/lang/String.<init>([BLjava/lang/String;)V```. The fixed code looks like its counterpart in INVOKESTATIC and INVOKEVIRTUAL.

Work towards JACOBIN-386

---

src/classloader/javaLangString.go
src/exceptions/exception.go

* Added StringIndexOutOfBoundsException to the list of exceptions.
* Work on ```javaLangString.go```
- Filled in the Load_Lang_String map with all of the documented constructors. Source: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html
- Re-sorted the map entries to be in the same order as the Java String API documentation.
- Noted as a comment when jacobin and the Java library functions are working well together so that is why jacobin need not implement a replacement.
- Completed code for ```new String(bytes)``` and ```new String(bytes, offset, length)```.
- The remaining constructors that we are postponing are directed to the String standard exception handler, ```noSupportYetInString```.
- Regarding the  remaining member functions (gadzillions), one …

More progress on JACOBIN-386

---

src/classloader/javaIoPrintStream.go
src/classloader/mTable.go
src/jvm/goFunctionExec.go

Re: JACOBIN-387
**classloader/javaIoPrintStream.go and mTable.go**
- GMeth is used in several classloader source files.
-  So, I moved the GMeth type definition from javaIoPrintStream.go (one of the users) to mTable.go which I perceive as a central-ish definition file for classloader.
**classloader/mTable.go, jvm/goFunctionExec.go**
- After I did the move, I saw that GMeth and GmEntry are duplicate type definitions.
- I replaced GmEntry with GMeth in mTable.go and goFunctionExec.go. I favored GMeth because there are many GMeth references in classloader files.
-  I also replaced "Fu" references by "GFunction".
**jvm/goFunctionExec.go**
Implemented a local tracing boolean (localDebugging) in runGframe and runGmethod to avoid tracing the whole world. So, tracing in both functions will occur …

Centralise GMeth + goFunctionExec.go local tracing

---

src/object/object.go
src/object/object_test.go

Files affected:
- object/object.go
- object/object_test.go
Sample console output:
```
=== RUN   TestObjectToString1
object_test.go:15: Test field table toString processing
object_test.go:84: java/lang/madeUpClass
Fld: myString: (Ljava/lang/String;) Hello, Unka Andoo !
Fld: myFloat: (F) 1.000000
Fld: myStaticTrue: (XZ) true
Fld: myFalse: (Z) false
Fld: myChar: (C) 'C'
Fld: myByte: (B) 61
Fld: myDouble: (D) 2.000000
Fld: myInt: (I) 42
Fld: myLong: (J) 42
Fld: myShort: (S) 42
--- PASS: TestObjectToString1 (0.00s)
=== RUN   TestObjectToString2
object_test.go:90: Test field slice toString processing
object_test.go:97: java/lang/String
Fld:([B) This is a compact string from a Go string
object_test.go:111: java/lang/madeUpClass
Fld:([B) 54 68 69 73 20 69 73 20 61 20 63 6f 6d 70 61 63 74 20 73 74 …
```

contribution to JACOBIN-395

---

src/classloader/javaIoPrintStream.go

```
// Print string
func PrintS(i []interface{}) interface{} {
// TODO: Eventually will need to check whether or not i[1] is a compact string.
//       Presently, we assume it is.
switch i[1].(type) {
case *object.Object:
strAddr := i[1].(*object.Object)
t := (strAddr.Fields[0].Fvalue).(*[]byte)
fmt.Print(string(*t))
case string:
str := i[1].(string)
fmt.Print(str)
}
return nil
}
```

JACOBIN-396 Fix PrintS to support 2 input types

---

src/classloader/javaIoPrintStream.go
src/classloader/javaLangString.go

After playing wack-a-mole this morning, I finally came down to the conclusion that there is only 1 type of interface that PrintS need entertain: *object.Object.
The issues overcome:
* StringFormatter in javaLangString.go was returning a Go string. This contradicts other String variables which are initialized or receive their value in some other way. The correct type to return from StringFormatter is *object.Object. 
* PrintS has been corrected to only look for an *object.Object interface.
* My Java language test driver previously did not have enough individual cases. Now, it has more!

JACOBIN-396, only 1 PrintS interface

---

src/classloader/javaLangString.go
src/classloader/javaPrimitives.go
src/classloader/mTable.go
src/jvm/run.go
src/object/object.go
src/object/object_test.go

Whichever is there, use it, preferring FieldTable. 
E.g.
```double dd = 3.0d;```
uses the FieldTable where the key="value" table entry holds the double floating-point value (3.0 in this example).
**Summary**  
All primitives are working as expected.
**Exceptions**
- Inside the format string, %% is not recognized as meaning one % character.
- Inside the format string, %n is not recognized as meaning one \n character.
- %b and %B will not work for booleans. One has to specify %t or %v. No option to capitalize oboolean output.
**Use of object.ToString**
I incorporated object.ToString into the run.go emitTraceData function.
Note the new indentation parameter.
Reaction?

JACOBIN-393 StringFormatter: handle primitives (int, short, etc.)

---

src/classloader/javaLangString.go
src/jvm/run.go
src/object/object.go

* ```classloader/javaLangString.go``` - Commented out a left-over DEBUG printf.
* ```jvm/run.go``` - use the object.IsNull function which checks for 2 possible nil conditions.
* ```object/object.go``` - guard against (a) nil klass pointer and (b) object which has no field information in FieldTable nor in the Fields slice.
In tracing jacotest case ```stringer-2```, it was observed that under some string-handling circumstances, both of the above object anomalies occured. Needs further analysis as to why.

tracing issues, object issues

---

src/classloader/javaLangString.go
src/exceptions/errors.go
src/exceptions/exception.go
src/object/object.go

* ```object.go```: In some of the exception-runaway instances, FieldTables and Fields slices were 1/2-baked. In tracing, note these nil pointers instead of crashing.
* ```object.go```: When formatting fields for tracing, it was noticed that byte array output ([B) sometimes showed a blank value. These were actually nil strings. Added double-quotes (") as brackets to string formatting.
* ```exception.go```: Added temporary code to cease execution in ```Throw``` to eliminate the runaway effect (E.g. ```PUTSTATIC: type unrecognized: <nil>```). Yes, I did check the JacobinName for "test" (pesky unit tests!).
* ```JavaLangString.go```: New G functions: objectRef.toLower and objectRef.toUpper. Trying to avoid Locale as much as possible.

object protect field pointers against nil; use string quotes

---

src/object/object.go
src/object/object_test.go

While tracing, if there are field formatting errors for any reason, we will now dump the entire object.
Error conditions diagnosed in ```FormatField```:
* <ERROR nil class pointer!>
* <ERROR FieldTable["value"] not found!> when FieldTable is nonempty
Error conditions diagnosed in ```fmtHelper (called by FormatField)```:
* <ERROR Ftype=bool but unexpected Fvalue variable type: observed-type !>
* <ERROR nil Fvalue!> E.g. Ftype is [B but the byte array pointer is nil
An object dump will always attempt to depict both the FieldTable contents and the Fields slice contents.
See the ```object/object_test.go``` unit testing.
E.g. Dump an object with a non-empty FieldTable but an empty Fields slice:
```
DumpObject java/lang/madeUpClass {
Class: java/lang/madeUpClass
Field Table:
Fld myChar: (C) 'C' …
```

JACOBIN-398 While tracing, FormatField returning "<ERROR..." --> DumpObject(title=why?/what?, indentation=0)

---

src/jvm/instantiate.go
src/object/object.go
src/object/object_test.go

1. In i```nstantiate.go```, use types.Static instead of literal "X".
```
if f.IsStatic {
// in the instantiated class, add a types.Static before the
// type, which notifies future users that the field
// is static and should be fetched from the Statics
// table.
fieldToAdd.Ftype = types.Static + presentType // <------------------ replaced "X"
}
```
2. ```DumpObject```: show FieldTable number of fields (like as done with the Fields slice).
3. ```FormatField```: check slices first. If the slices are non-empty, use the first element. This reduces significantly the number of diagnostic DumpObject calls made by FormatField for FieldData (map) which lacks a "value" element.
4. ```FormatField```: make the FieldData, Fields, and default code sections more independent so that it would be quite …

Miscellaneous Minor Tweaks

---

src/classloader/javaLangString.go
src/classloader/javaPrimitives.go
src/exceptions/exception.go
src/object/object.go

Files updated:
- classloader/javaPrimitives.go - fixed JACOBIN-403. Also, implemented a standard "just return" ```<clinit>``` function for the primitives. Bye-bye stack trace heaviness!
- object/object.go - added function MakePrimitiveObject, moved from javaPrimitives.go.
- exceptions/exception.go - added NumberFormatException.

JACOBIN-403 javaPrimitives.go mystery solved

---

src/classloader/javaIoPrintStream.go
src/classloader/javaLangString.go
src/jvm/run.go
src/object/String.go
src/object/object.go

- run.go GETFIELD: If the field type is a string, wrap it in an object and push the object address onto the stack.
- run.go ARRAYLENGTH: Pointer to an array of objects is also a possibility.
- javaIoPrintStream.go Println & PrintS: Be prepared for *object.Object as well as *[]byte.
- String.go: added StringClassFdesc = "Ljava/lang/String;"
- object.go: Be prepared for *object.Object as well as *[]byte.
Note that exceptions.Throw (temporary code, to be replaced by Andrew's WIP) is duplicating the normal ShowPanicCause logging of a severe error message. This causes double-reporting in jacotest. I tried a fix by taking the log call out of of the temporary Throw function but this blew up several unit tests. Working on this. This can be addressed in jacotest as mentioned in JACOBIN-405.

Fix GETFIELD, ARRAYLENGTH; Watch out for *object.Object in object.go, javaIoPrintStream.go

---

src/classloader/javaIoPrintStream.go
src/classloader/javaLangClass.go
src/classloader/javaLangString.go
src/classloader/javaLangSystem.go
src/jvm/instantiate.go
src/jvm/jvmStart.go
src/jvm/option_table_loader.go
src/jvm/run.go
src/jvm/run_test.go
src/object/object.go
src/object/object_test.go
src/statics/statics.go

This is a first attempt at getting the object package functions FormatField and DumpObject to access the Statics table when fields are of ```types.Static```.
Ran into a Go diagnostic about a cycle (A calls B who calls C who calls A). Solved this by creating package ```statics``` and moving ```statics.go``` there. Added function ```GetFieldValue``` and ```DumpStatics``` to that source file. Unfortunately, a number of files were impacted by the package name change. 
**The list of impacted source files by this PR:**
new file:   src/statics/statics.go
deleted:    src/classloader/statics.go
modified:   src/classloader/javaIoPrintStream.go
modified:   src/classloader/javaLangClass.go
modified:   src/classloader/javaLangString.go
modified:   src/classloader/javaLangSystem.go
modified: …

JACOBIN-406 Tracing statics should show values from Statics table

---

src/jvm/TestHello2Class_test.go

On a jacobin or other failure, TestHexHello2ValidClass was only showing stdout which is probably nil. Now, it shows both stdout and stderr on failure.

Fix unit test TestHexHello2ValidClass

---

src/gfunction/javaLangThrowable.go
src/globals/globals.go
src/jvm/cli.go
src/jvm/cli_test.go
src/jvm/jvmStart.go
src/jvm/option_table_loader.go

Updated sources:
```
modified:   src/globals/globals.go - created the fakeInstantiateClass function
modified:   src/jvm/jvmStart.go - work from a pointer to global like everyone else
modified:   src/gfunction/javaLangThrowable.go - When an error is returned from InstantiateClass,
return a nil value for *object.Object.
```
Refactored in jvmStart.go: Global --> globPtr, so variable name change only:
```
modified:   src/jvm/cli.go
modified:   src/jvm/cli_test.go
modified:   src/jvm/option_table_loader.go
```

JACOBIN-412 make the global struct a singleton across all packages

---

src/gfunction/gfunction.go
src/gfunction/javaLangObject.go
src/gfunction/javaLangSystem.go
src/gfunction/javaPrimitives.go
src/gfunction/jdkMiscUnsafe.go
src/jvm/run.go

* In run.go CHECKCAST, when the array types do not match:
- Commented out the Throw set up and execution. Let it continue with a warning, pending resolution of JACOBIN-413.
- TODO comment inserted as a reminder.
* Centralised all of the *justReturn() G functions in one, located in gfunction/gfunction.go. Only one is enough.
One can see 2 jacotest cases, ```stringer-1``` and ```vector-survivor-2```, continuing on to attempt an INVOKEINTERFACE:
* ```stringer-1``` attempts a String.contains(CharSequence).
* ```vector-survivor-2``` attempts a Vector(Collection).

Move along some jacotest failures to INVOKEINTERFACE

---

src/gfunction/gfunction.go
src/gfunction/javaLangStringBuilder.go
src/jvm/run.go

Mods:
* Added an ```isLatin1``` Go method to new source file ```javaLangStringBuilder.go```. Always true. Someday, it meeds to be a real test as indicated by the TODO comment.
* Fixed run.go PUTFIELD to diagnose a missing superclass field.

Move 2 jacotest cases past isLatin1 native function

---

src/classloader/classes.go
src/classloader/mTable_test.go
src/gfunction/javaLangString.go
src/jvm/goFunctionExec.go
src/jvm/run.go
src/util/execUtilities.go
src/util/execUtilities_test.go

* Fix JACOBIN-420 : Context - execUtilities.go ParseIncomingParamsFromMethTypeString. While scanning the input string and detecting case '[' (array), the element type is ascertained. But, when the type indicates a reference array (L), we were not flushing to the semicolon (;) as the parallel case 'L' does. This has been addressed to employ the same flushing technique.
* Fix JACOBIN-420 : Context - execUtilities.go ParseIncomingParamsFromMethTypeString. Was not checking for the error cases:
- No semicolon present to terminate an L element.
- In the array case, no element type present (encountered a right parenthesis immediately after the last [-character).
- Illegal characters that start an element type.
* Fix JACOBIN-421 : new String issues. First parameter now holds the …

Fix JACOBIN-420/421 + logTraceStack enhancement + show statics table

---

src/statics/statics.go
src/statics/statics_test.go

statics.go (updated)
* DumpStatics - Presort in key sequence before printing. Note that upper case entries come first (normal for Unix, Linux, and MacoS).
* AddStatic - Yell when something goes wrong (SEVERE).
statics_test.go (new) - unit tests.

JACOBIN-424 : statics.go (update), statics_test.go (new)

---

src/object/object.go
src/object/object_test.go

* Stop ```object.go fmtField``` from complaining about no name in slice fields.
* Always show the field type static prefix (X) if it is present.
* Improved comments.

JACOBIN-426 and reworking a bit of DumpObject

---

src/jvm/run.go

```
case opcodes.I2S: //	0x93 convert int to short
intVal := pop(f).(int64)
shortVal := int16(intVal) // Java shorts are 16-bit unsigned values
push(f, int64(shortVal))
```

fix JACOBIN-434

---

src/jvm/arrays_test.go
src/jvm/run.go
src/object/arrays.go

See discussion in 
https://jacobin.myjetbrains.com/youtrack/issue/JACOBIN-439/object.Make1DimArray-should-not-be-used-to-create-a-Reference-Array
Modifications:
* jvm/run.go NEWARRAY: Diagnose references as well as ERROR.
* jvm/arrays_test.go: 
- Fixed the unit tests.
- Added unit test ```TestNewrrayInvalidTypeRef```.
- Renamed unit test ```TestNewrrayInvalidType``` to ```TestNewrrayInvalidTypeError```.
- Changed ```TestAastore``` to use NEWARRAY (as coded) but with an integer array. There is an ANEWARRAY test subsequently in unit test ```TestAnewrray```.

JACOBIN-439 Inhibit warning message for multidimensional REF arrays

---

.github/workflows/go.yml
codecov.yml

**JACOBIN-444**
The original versions of github actions workflow .yml files for boith jacobin and jacotest.go were based on github actions examples that make use of versioned copies of actions. However, most folks (users) simply want the "latest, stable" version. 
This has been an irritant for some time. The solution has been available for a long time: use a version reference of "main".
E.g. ```uses: actions/checkout@v3``` -----> ```uses: actions/checkout@main```
**JACOBIN-445**
There is no codecov.yml file. I am trying out a simple, informational-only file.

JACOBIN-444, JACOBIN-445

---

.github/workflows/go.yml
codecov.yml

As @platypusguy stated in JACOBIN-445, there is no current need to do code coverage processing in the github actions workflow. Should the need arise in the future, we can readily add those steps.

Jacobin does not currently need codecov in github actions

---

src/exceptions/throw.go
src/gfunction/gfunction.go
src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangMath.go
src/gfunction/javaLangString.go
src/gfunction/javaLangSystem.go
src/gfunction/jdkMiscUnsafe.go
src/jvm/TestHexIDIVexception_test.go
src/jvm/goFunctionExec.go
src/jvm/run.go

Impacted source code:
- exceptions/throw.go
- jvm/TestHexIDIVexception_test.go
- jvm/goFunctionExec.go
- jvm/run.go
- gfunction/gfunction.go
- gfunction/javaIoPrintStream.go
- gfunction/javaLangMath.go
- gfunction/javaLangString.go
- gfunction/javaLangSystem.go
- gfunction/jdkMiscUnsafe.go
More and more.
Little by little.
No javaPrimitives.go functions yet.

JACOBIN-450 Base of G migration + 6 converted math functions + more

---

src/gfunction/javaPrimitives.go

Last `gfunction` file migrated: `javaPrimitives.go`
Work remaining (JACOBIN-451):
- `jvm/run.go` - Migrate throw calls, exceptions.Throw(n, msg) --> exceptions.ThrowEx(n, msg, f).
- `exceptions/exception.go` - remove function Throw.

JACOBIN-450 Migrate javaPrimitives.go to new scheme for G function exceptions

---

src/gfunction/javaLangString_test.go

It's helpful when looking through failed unit test results to see the expected value as well as the observed value.

Suggestion for unit tests: add display of expectation

---

src/gfunction/javaLangThrowable_test.go
src/gfunction/javaPrimitives.go
src/gfunction/primiFactory.go

This does not include statics table considerations.
It is an alpha-ish introduction.
Run jacotest 3.0.7 against it: W-L 48-63.
Thinking about splitting javaPrimitives.go by class:
* javaLangByte.go
* javaLangInteger.go
etc.

Introduced primitive factory - related to JACOBIN-455

---

src/gfunction/javaPrimitives.go
src/gfunction/primiFactory.go
src/statics/loadPrimiStatics.go
src/statics/statics.go

* Preloads for classes Byte, Character, Double, Float, Long, Math/StrictMath, and Short are compiled but not yet called by statics::PreloadStatics().
* The Integer statics preload are fully active.
* primiFactory::populator supports all primitives and does everything; went to school on stringClinit.
* All statics loaders have a name that follows a pattern: LoadStaticsX where X = String, Integer, Byte, etc.

JACOBIN-456 Integer only

---

src/gfunction/javaIoPrintStream.go

We still need to find out the root cause of JACOBIN-462.
The signature for gfunction/javaIoPrintStream.go Println() is java/io/PrintStream.println(Ljava/lang/String;)V.
But, the incoming argument (params[1]) is of type []byte.
In hindsight after looking at the frame locals, I've come to the conclusion that Println should accept both types in params[1]:
* *object.Object - originating from simple String variables
* []byte - originating from String fields of an object

JACOBIN-462 Self-protection and flexibility updates to gfunction/javaIoPrintStream.go

---

src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangString.go
src/gfunction/javaUtilLocale.go
src/object/format.go

* javaUtilLocale.go functions were returning an Object. However, the return should be nil. Just as with javaLangString.go functions that return nil, we should instead update the object indicated in params[0].
* javaIoPrintStream.go::PrintS must handle []byte as well as objectified strings in params[1].
* javaLangString.go::newStringFromBytesSubset, like newStringFromBytes, must handle []byte in params[1] as well as objectified strings.
How did I find these? In the jacotest.go/logs directory, I grepped "gfunction" on all the individual log files. Hits:
* JACOBIN-0322-default-locale
* JACOBIN-0325-super-1
* stringer-2

Fixes to Locale, String, and Print handling

---

src/jvm/run.go

Only source file run.go ARRAYLENGTH is amended.

JACOBIN-473 ARRAYLENGTH should handle int & float arrays

---

src/classloader/methArea.go
src/classloader/parser.go
src/jvm/run_LL-end_test.go
src/object/String.go
src/object/StringRepo.go
src/object/String_new-ish_test.go
src/object/String_repo_mid_level_test.go
src/object/String_repo_primitives_test.go
src/object/format.go
src/object/format_test.go
src/statics/statics_test.go

String repository source file changes:
- new file:   object/StringRepo.go - all of the new string repository functions go here
- new file:   object/String_repo_mid_level_test.go - Test mid-level functions
- new file:   object/String_repo_primitives_test.go - Test primitive functions
- modified:   object/String.go - Repo functions moved to StringRepo.go
- deleted:    object/String_new-ish_test.go - renamed as object/String_repo_primitives_test.go
- modified:   object/format.go - Dump Object is now conscious of types.StringIndex
The other file changes were to make use of the symbolic types definitions. No functional changes were made.

JACOBIN-463 String Repo functions, separate from older ones

---

src/jvm/goFunctionExec.go

```runGmethod``` was using a raw golang-list API to remove the top of the frame stack on a successful conclusion of a G method. This has been fixed to:
* use ```frames.PopFrame``` instead
* check for any returned errors

JACOBIN-474 use existing function to pop frame after gfunction completes

---

src/gfunction/javaLangString.go
src/jvm/arrays_test.go
src/jvm/run.go

See discussion in JACOBIN-475.
Files impacted:
* jvm/arrays_test.go
* jvm/run.go
Opcodes impacted: I/C/S/L/F/D -ALOAD and -ASTORE. In a nutshell, do not assume that the stack input is of type *object.Object. It could also be an array ([]int64 or []float64) per GETFIELD.
AALOAD and AASTORE seem okay but need to be verified.

JACOBIN-475 : array load/store opcodes handle objects or arrays

---

src/classloader/mTable.go
src/classloader/methArea_test.go
src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangString.go
src/jvm/run.go

* Added nil pointer protection to print and println of objects.
* Added comments to java/lang/String functions.
* Added method signature to error messages in run.go.
* Added a unit test to demonstrate that we can find class/method/signature with FetchMethodAndCP after those classes are loaded.
* stringConcat is more flexible BUT ........................
Somewhere, in jacobin, a Field is being set with Ftype="T" but Fvalue is a byte array. Ftype=[B is correct for an external string to/from a Hotspot library routine. See JACOBIN-479. Once we have set the new string strategy in motion, this symptom might disappear.

JACOBIN-477 and more

---

src/experimental/string.go
src/experimental/string_test.go

- One correction to string.go NewStringObject: Fvalue is a byte array per commentary.
- One correction to string.go GoStringFromStringObject: Fvalue is a byte array.
- One addition to string.go needed for javaLangString.go: UpdateStringObjectFromBytes.
- Unit test go file: string_test.go

JACOBIN-480 Adds/updates to package experimental

---

src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangString.go

* newStringFromBytes - accept [B or [B inside object
* newStringFromBytesSubset - ditto
* newStringFromChars - accept [C or [C inside object (one C is an int64)
* PrintlnString - accept [B or string object
* PrintString - ditto
Added function repeat to java/lang/String.

JACOBIN-477 Added flexibility to paramerter type in native string functions

---

src/gfunction/gfunction.go
src/gfunction/javaIoConsole.go
src/gfunction/javaLangString.go
src/jvm/cli.go

modified:   gfunction/javaIoConsole.go
All flexibilities were removed.

JACOBIN-482 : gfunctions now use array objects for parameters and results

---

src/jvm/run.go
src/jvm/runUtils.go
src/jvm/runUtils_test.go

Changed the name.
Added a case for int64.
Default ---> TRAP exceptions.throw
None of the unit tests nor the jacotest cases are hitting the default -- so far.

JACOBIN-483 convertIntegralValueToInt64

---

src/jvm/run.go

Java source:
```
import java.io.File;
public class main {
public static void main(String[] args) {
System.out.println("========================================= NEXT IS File file = new File(\"./data.txt\");");
File file = new File("./data.txt");
}
}
```

JACOBIN-486 (no fix) Show more evidence in PUTFIELD crash (java.io.File)

---

src/jvm/run.go

Jacobin was diagnosing native methods in INVOKEVIRTUAL.
Adding similar diagnosis to:
- INVOKESPECIAL
- INVOKESTATIC
Sample source:
```
public class main extends SuperDuperClass {
public main() {
// It was expected that invokespecial is used implicitly to invoke the superclass constructor,
// which in turn calls the native method.
// However, this code still went to INVOKEVIRTUAL in spite of Oracle docs.
// It may be the fault of my design.
super();
}
public native static int fnstatic();  // -----------------> INVOKESTATIC
public static void main(String[] args) {
System.out.println("main: Calling fnstatic next .....");
fnstatic();
System.out.println("main: Calling new SubClass() next .....");
new main();
}
}
class SuperDuperClass {
public native void fnspecial();
public SuperDuperClass() { …
```

JACOBIN-486 Add diagnostic data to native method calls

---

.github/workflows/go.yml

Github Actions workflow succeeds but there is the same warning for each O/S:
The fix in the commit is based on a discussion at https://github.com/actions/setup-go/issues/427

JACOBIN-491 Github Actions workflow fix for golang projects

---

.github/workflows/go.yml

I forgot that Windows was a separate build from MacOS and Linux.

JACOBIN-491 Update go.yml Windows section to resolve caching issue

---

src/classloader/classes.go
src/gfunction/Traps.go
src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangSystem.go
src/jvm/run.go

* The SecurityManager is deprecated so trapping it as such.
* Added MethodSignatures entry for arraycopy to ```javaLangSystem.go```:
```
MethodSignatures["java/lang/System.arraycopy.(Ljava/lang/Object;ILjava/lang/Object;II)V"] =
GMeth{
ParamSlots: 5,
GFunction:  arrayCopy,
}
```

JACOBIN-476 trap SecurityManager, enable java/lang/arraycopy

---

src/exceptions/exception.go
src/exceptions/throw.go
src/gfunction/Traps.go

The ThrowEx hello message contains the original detailed error message. That is ok for tracing.
It would be very helpful in debugging if we also log in the caught and uncaught sections as SEVERE. Then, even if the original detailed error message gets lost or some other mishap occurs, we will at least have:
* captured the original detailed message as evidence
* note that we have come through ThrowEx and the mode (caught or uncaught)

JACOBIN-499 Always show the ThrowEx caught and uncaught messages

---

src/gfunction/javaLangSystem.go
src/jvm/run.go

* In INVOKEINTERFACE, compare to classloader type classloader.Interface instead of classloader.MethodRef for CP entry type diagnosis.
* In ISTORE_n, tolerate a uint8 as an integer in addition to int64. Default action: report an error.

JACOBIN-501 Expand ISTORE to tolerate uint8 as int

---

src/frames/frames.go
src/gfunction/Traps.go
src/gfunction/gfunction.go
src/gfunction/gfunction_test.go
src/gfunction/javaUtilConcurrentAtomicAtomicInteger.go
src/gfunction/javaUtilHexFormat.go
src/gfunction/jdkMiscUnsafe.go
src/globals/globals.go
src/jvm/goFunctionExec.go
src/jvm/run.go

* Added traps for more deprecated functions.
* Added traps for Filter{Input, Output}Stream classes.
* Created a ```<clinit>``` for java/util/HexFormat to avoid the SharedSecrets cascade of trouble:
```
GETFIELD: Invalid type of object ref: int64
error encountered running java/lang/invoke/MethodHandles$Lookup.<clinit>()
NEW: could not load class java/lang/invoke/MethodHandles$Lookup
INVOKESTATIC: error running initializer block in jdk/internal/access/SharedSecrets
INVOKESTATIC: error running initializer block in java/util/HexFormat
Method: java/lang/Class.getModule                PC: 003
Method: java/lang/invoke/MethodHandles$Lookup.<clinit> PC: 028
Method: java/lang/invoke/MethodHandles.lookup    PC: 002
Method: java/lang/invoke/MemberName.getFactory   PC: 003
Method: …
```

JACOBIN-469 Miscellaneous native work-arounds, AtomicInteger

---

src/exceptions/throw.go
src/gfunction/Traps.go
src/gfunction/gfunction.go
src/gfunction/javaIoPrintStream.go
src/jvm/TestHexIDIVexception_test.go
src/jvm/run.go

* Alphabetised method signature table entries in gfunction/Traps.go.
* Fixed a few entries in gfunction/Traps.go.
* Centralised the map table of all method  signatures by moving the Go map to gfunction/gfunction.go.
* In the run.go op codes, return with error object only if testing.
* In throw.go, watch out for a corrupted glob.Threads map. Why is it happening?

JACOBIN-502 gFunction cleanup and minor fixes

---

src/classloader/TestLoadClass_test.go
src/classloader/classes.go
src/classloader/classes_test.go
src/classloader/classloader.go
src/classloader/classloader_test.go
src/classloader/jmodMap_test.go
src/classloader/methArea.go
src/classloader/methArea_test.go
src/classloader/parser.go
src/classloader/parser_test.go
src/classloader/parsingFullClass_test.go
src/gfunction/javaLangString.go
src/globals/globals.go
src/jvm/arrayBytecodes_test.go
src/jvm/initializerBlock.go
src/jvm/instantiate.go
src/jvm/instantiate_test.go
src/jvm/run.go
src/jvm/runUtils.go
src/jvm/run_A-E_test.go
src/jvm/run_F-IF_test.go
src/jvm/run_II-LD_test.go
src/object/format.go
src/object/string.go
src/object/string_test.go
src/statics/statics_test.go
src/types/constants.go

In the first go-around,
- Move some java/lang/String related constants from objects.string.go to types/constants.go, joining the java/lang/Object constants. Now, they are all in one place.
- In several Go source files, change references to literals such as "java/lang/String" and "java/lang/Object" to use constants defined in types.constants.go.
Deferred:
- "value"
- empty string ("") --> types.EmptyString
- others, TBD

JACOBIN-510 Consolidate Go constants to types/constants.go

---

src/jvm/run.go

Misleading error message in INVOKEINTERFACE:
```INVOKEINTERFACE: CP entry type (%d) did not point to an interface method type (%d)```
Overridden in a subsequent assignment statement to:
```INVOKEINTERFACE: WIP, forcing an error, for the nonce /* TODO Remove this temporary error message */```
When INVOKEINTERFACE is ready for testing, we should yank this message along with the other indicated changes.

JACOBIN-500 temporary error msg in INVOKEINTERFACE

---

src/frames/frames.go
src/jvm/run.go

I was trying figure out why stack underflow was occuring. I suspected that it might be due to ThrowEx appending the wrong ```frame.meth``` in the case that the exception occured in a called local function. Now, I don't think so. Are we getting confused somehow with the runGmethod-runFrame-runGframe stuff? I cannot see it but maybe I overlooked something.
The following works as expected, correctly reporting a symptom of ByteArrayInputStream not yet supported:
```
import java.io.ByteArrayInputStream;
import java.io.InputStreamReader;
public class main {
public static void main(String args[]) { 
byte[] byte_array = { 'w' };
ByteArrayInputStream bais = new ByteArrayInputStream(byte_array);
InputStreamReader streamreader = new InputStreamReader(bais);
String str = streamreader.getEncoding(); …
```

JACOBIN-495 Reinstated frame push/pop debug (currently, turned off)

---

src/gfunction/gfunction.go
src/gfunction/javaAwtGraphicsEnvironment.go
src/gfunction/justReturn.go
src/globals/globals.go

Three of the AWT functions are preventing jacotest case emission-line-spectra from showing a true result.
Source files modified:
* gfunction/gfunction.go -- load javaAwtGraphicsEnvironment entries
* gfunction/nilClinit.go --renamed--> gfunction/justReturn.go
* gfunction/justReturn.go -- added more justReturns.
* globals/globals.go  -------------------------------------------- isHeadless(), isHeadlessInstance()
New: gfunction/javaAwtGraphicsEnvironment.go   ------- support isHeadless(), isHeadlessInstance()

JACOBIN-511 Three AWT functions are blocking jacotest case emission-line-spectra

---

src/gfunction/Traps.go
src/gfunction/javaIoBufferedReader.go
src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangMath.go
src/gfunction/javaLangString.go
src/gfunction/javaLangSystem.go

Updated source files:
* gfunction/Traps.go
* gfunction/javaIoBufferedReader.go
* gfunction/javaIoPrintStream.go
* gfunction/javaLangMath.go
* gfunction/javaLangString.go
* gfunction/javaLangSystem.go
Note that 
* gfunction/gfunction.go calls ThrowExNil if an error is encountered during MethodSignature loading.
* gfunction/javaLangThrowable_test.go calls to ThrowEx as part of testing logic.

JACOBIN-514 G functions should return the standard G error block

---

src/gfunction/javaLangLong.go
src/gfunction/javaLangString.go
src/gfunction/justReturn.go
src/jvm/run.go

* run.go line 184 - The separator is a colon. Also, added a check that a colon was found.
* String.isLatin1 - always return true.
* Long.toHexString - needed in one jacotest case.

JACOBIN-495 Correct split character on error message, add gfunctions

---

src/jvm/run.go

JACOBIN-518 return non-nil error objects from runFrame to runGmethod when runGframe returns an error

---

src/gfunction/Traps.go
src/gfunction/javaLangInteger.go
src/jvm/run.go
src/jvm/runUtils.go

Modified: run.go - Fix error handling in runFrame after calling runGframe.

JACOBIN-518 fix caught G exceptions in run.go runFrame

---

src/exceptions/catchFrame.go
src/gfunction/Traps.go
src/gfunction/javaIoFileWriter.go
src/gfunction/javaIoInputStreamReader.go
src/gfunction/javaIoOutputStreamWriter.go
src/gfunction/javaMathBigInteger.go
src/types/javaTypes.go

**JACOBIN-523**: correct originator in logging
modified: exceptions/catchFrame.go
**JACOBIN-524**: adopt gfunctionExec.go strategy of error reporting
modified:   gfunction/Traps.go
modified:   gfunction/javaIoFileWriter.go
modified:   gfunction/javaIoInputStreamReader.go
modified:   gfunction/javaIoOutputStreamWriter.go
more to come in the future!
**JACOBIN-517**: BigInteger
- All BigInteger member functions are now accounted for although some of them are trapped.
- jacotest cases big-integer and big-integer-2 both pass.

JACOBIN-523 and JACOBIN-524 and JACOBIN-517

---

src/gfunction/Traps.go
src/gfunction/javaIoBufferedReader.go
src/gfunction/javaIoConsole.go
src/gfunction/javaIoFile.go
src/gfunction/javaIoFileInputStream.go
src/gfunction/javaIoFileOutputStream.go
src/gfunction/javaIoFileReader.go
src/gfunction/javaIoFileWriter.go
src/gfunction/javaIoInputStreamReader.go
src/gfunction/javaIoOutputStreamWriter.go
src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangByte.go
src/gfunction/javaLangClass.go
src/gfunction/javaLangDouble.go
src/gfunction/javaLangInteger.go
src/gfunction/javaLangLong.go
src/gfunction/javaLangMath.go
src/gfunction/javaLangStackTraceElement.go
src/gfunction/javaLangString.go
src/gfunction/javaLangStringBuilder.go
src/gfunction/javaLangStringUTF16.go
src/gfunction/javaLangSystem.go
src/gfunction/javaLangSystem_test.go
src/gfunction/javaLangThread.go
src/gfunction/javaMathBigInteger.go
src/gfunction/javaNioCharsetCharset.go
src/gfunction/javaUtilHashMap.go
src/gfunction/javaUtilRandom.go
src/gfunction/jdkInternalMiscUnsafe.go

@platypusguy As we discussed, error block text no longer includes the function name since the class name, method name, and method type will be supplied by runGfunction.
modified:   gfunction/Traps.go
modified:   gfunction/javaIoBufferedReader.go
modified:   gfunction/javaIoConsole.go
modified:   gfunction/javaIoFile.go
modified:   gfunction/javaIoFileInputStream.go
modified:   gfunction/javaIoFileOutputStream.go
modified:   gfunction/javaIoFileReader.go
modified:   gfunction/javaIoFileWriter.go
modified:   gfunction/javaIoInputStreamReader.go
modified:   gfunction/javaIoOutputStreamWriter.go
modified:   gfunction/javaLangByte.go
modified:   gfunction/javaLangClass.go
modified:   gfunction/javaLangDouble.go
modified:   gfunction/javaLangInteger.go …

JACOBIN-524 and small error text fixes

---

src/gfunction/javaLangString.go
src/jvm/gfunctionExec.go

JACOBIN-528: Solve byte case of formatting string output with specifier %x
Its a one-line fix in function sprintf of javaLangString.go. See line 527.
JACOBIN-529: Identify class and method of G function in error message.

JACOBIN-528, JACOBIN-529

---

src/gfunction/javaLangLong.go
src/gfunction/javaUtilRandom.go

* Add a Long.toString function for some jacotest cases.
* There was no need to have two golang functions for both Random.nextInt and Random.nextLong. The two method signatures can map to a single function.
* There was never a reason to have a randomNextLongBound function since there is no such API. The method signature and function should be deleted.

JACOBIN-531 Maintenance on classes java/lang/Long and java/util/Random

---

src/jvm/run.go

Update CHECKCAST to include the invalid data alluded to in its diagnostic messages. See lines 2792 and 2810.
TODO: Check the other op code cases for missing evidence.

JACOBIN-532 include diagnosed data in error messages

---

src/gfunction/javaLangInteger.go

It turns out that the we did not have a G function for "java/lang/Integer.parseInt(Ljava/lang/String;)I" (no radix specified). This gave us questionable results by using the OpenJDK JVM library function.
This has been added as a G function.

JACOBIN-525 add Integer.parseInt(string without radix)

---

src/jvm/run.go

Instead of returning an error, INVOKE* (4 of them) are calling ThrowEx.
impacted source: run.go

JACOBIN-540 INVOKE* and a few more use ThrowEx

---

src/jvm/run.go

Only INVOKESTATIC G and J were modified.
If this PR is approved, we should apply the same to INVOKEVIRTUAL and INVOKESPECIAL.

JACOBIN-542 unconditionally set f.ExceptionPC to f.PC just before modifying f.PC in INVOKESTATIC G & J

---

src/jvm/run.go

Solved IDIV, INVOKE*, LDIV,FDIV. etc. in one place: at the top of the main switch, f.ExceptionPC = f.PC so no need to do this anywhere else in run.go.

JACOBIN-542 Solved IDIV, INVOKE*, LDIV, FDIV. etc. in one place

---

src/jvm/gfunctionExec.go

See YouTrack.
One file impacted: runGfunction.go

JACOBIN-544 : Resurrect missing NeedsContext code in runGfunction

---

src/gfunction/javaLangString.go
src/jvm/run.go
src/jvm/runUtils.go

* jvm/run.go - ISTORE lines 575 and 578 expanded to tolerate non-int64 integers.
* jvm/runUtils.go - new function `convertInterfaceToInt64` (called in ISTORE).
* gfunction/javaLangString.go - new G functions replaceCC and split.

JACOBIN-547 Incremental fixes to support stringer-1

---

src/gfunction/Traps.go
src/gfunction/javaIoRandomAccessFile.go
src/gfunction/javaLangStackTraceElement.go
src/gfunction/javaLangSystem.go
src/gfunction/javaUtilLocale.go
src/gfunction/justReturn.go

Fixed in this PR.
Jacotest case fits is moved along to failing in java/text/SimpleDateFormat.

JACOBIN-548 jacotest case fits: failing on deprecated security

---

src/gfunction/gfunction.go
src/gfunction/javaLangSystem.go
src/jvm/gfunctionExec.go

Trying to head off access to deprecated classes and functions related to the deprecated Java security management.
E.g. There are OpenJDK library functions that call System.getSecurityManager.
Strategy: return null.

JACOBIN-549 System.getSecurityManager --> null

---

src/gfunction/Traps.go
src/gfunction/javaLangMath.go
src/gfunction/javaUtilHashMap.go
src/gfunction/justReturn.go
src/jvm/run.go
src/jvm/runUtils.go

- Mostly, as we discussed in email.
- In one case, the op code argument was illegal so, ```IllegalArgumentException```; in another, a required field was missing so ditto.
- "jdk/internal/access/SharedSecrets.<clinit>()V": trap --> justReturn.

JACOBIN-557 In most cases, VirtualMachineError --> InternalException

---

src/exceptions/catchFrame.go
src/exceptions/throw.go

The prefix is a clash with the Java exception "FindException".
This was driving jacotest bananas with the only remedy being do not include "FindException" in the ERROR_CATEGORIES.txt file.
Find --> Locate. Small rename with no impacts outside of catchFrame.go.

JACOBIN-558 Change "FindExceptionFrame" to "LocateExceptionFrame"

---

src/exceptions/catchFrame.go
src/gfunction/testGfunctions.go

Impacted source code:
modified:   exceptions/catchFrame.go
modified:   gfunction/testGfunctions.go

JACOBIN-561 Migrate use of InternalError to InternalException

---

src/gfunction/Traps.go
src/gfunction/gfunction.go
src/gfunction/javaLangString.go
src/gfunction/javaLangStringBuilder.go
src/gfunction/javaSecurityAccessController.go
src/object/string.go
src/object/string_test.go

* Neutralize that pesky Java security access control.
* Allow StringBuilder and StringBuffer (upcoming) to leverage the object/*.go functions.
* ObjectFieldToString does not have to be a warning-blabbermouth; set the log level to FINE.

JACOBIN-547 mostly StringBuilder append

---

src/gfunction/javaLangInteger.go
src/gfunction/javaLangString.go
src/gfunction/javaLangStringBuffer.go
src/gfunction/javaLangStringBuilder.go
src/gfunction/javaLangString_test.go
src/jvm/run.go

Amendments to javaLangStringBuilder.go:
* append
* insert
* delete, deleteCharAt
* more append
* compareTo
* more insert
* setCharAt
* setLength
Added function signum to javaLangInteger.go.
StringBuffer (not yet thread safe):
* Unique <clinit> and <init> functions.
* Uses StringBuilder member functions otherwise.
A thread safe strategy for G functions is proposed in JACOBIN-564.

JACOBIN-547 implement various functions in javaLangStringBuilder.go and  javaLangStringBuffer.go

---

src/classloader/methArea.go
src/gfunction/Traps.go
src/gfunction/gfunction.go
src/gfunction/javaLangString.go
src/gfunction/javaLangStringBuffer.go
src/gfunction/javaMathBigInteger.go
src/gfunction/javaUtilRandom.go
src/globals/globals.go
src/jvm/gfunctionExec.go

*  gfunction/gfunction.go - add ```ThreadSafe   bool``` to ```GMeth``` struct.
* gfunction/javaLangStringBuffer.go - add ```ThreadSafe: true``` everywhere except ```<clinit>``` (justReturn caller).
* Off topic but ..... gfunction/javaMathBigInteger.go - add ```signum``` field to object ```BigInteger```.
* jvm/gfunctionExec.go - use ```Gmeth.ThreadSafe``` boolean to govern the use of lock/unlock.
JACOBIN-547 - Add String <init> functions for argument types String, StringBuilder, & StringBuffer
JACOBIN-566 - Use standard ```globals.SleepMsecs``` (currently, = 5 msecs) in classloader/methArea.go, globals/globals.go, and jvm/gfunctionExec.go.

JACOBIN-564 StringBuffer usage of flag ThreadSafe

---

src/gfunction/javaLangString.go
src/gfunction/javaUtilRandom.go

Some ```TODO``` comment placeholders (will execute OpenJDK JVM functions for the moment), quite a number of traps, and some new G functions.
Impacted source files:
* java/lang/String
* java/util/Random

JACOBIN-547 filled out java/lang/String and java/util/Random

---

src/gfunction/javaLangString.go

Before this fix, ```String.intern()``` was diagnosed as a Java native function (true).
Fix: The G function stringIntern() simply returns the input String object.
**TODO** (marked in source code): Should we add the input string to the string pool if not yet present?
This fix peels the onion to this crash:
```
com.sun.jdi.InternalException: locateExceptionFrame: Method jdk/internal/misc/CDS.<clinit> not found in MTable
goroutine 1 [running]:
jacobin/exceptions.minimalAbort(0x2e, {0xc004889c70, 0x4f})
/home/elkins/BASIS/jacobin/src/exceptions/throw.go:282 +0x26
jacobin/exceptions.locateExceptionFrame(0xc00009a420, {0xc0048b92f0, 0x27}, 0x0)
/home/elkins/BASIS/jacobin/src/exceptions/catchFrame.go:67 +0x125
jacobin/exceptions.FindCatchFrame(0xc0038c2510, {0xc0048b92f0?, 0x1?}, 0x2?) …
```

JACOBIN-577 String.intern(), a native, called outside of String class

---

src/gfunction/javaLangInteger.go
src/gfunction/javaLangString.go
src/gfunction/javaUtilLocale.go

All of the Locale constructors are now deprecated.
3 undocumented and pesky Locale.getInstance functions are now returning the default Locale.

JACOBIN-577 some Locale cases; JACOBIN-578 add some String G functions

---

src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangString.go

modified:   src/gfunction/javaIoPrintStream.go
modified:   src/gfunction/javaLangString.go
Oddly enough, I ran into another case where a raw array was floating around run.go op codes:
```
char ch[] ..... ;
System.out.println(ch);
```
Yes, the array for `ch` should have been in a Jacobin object.

JACOBIN-555 added String.getChars and String.indexOf

---

src/gfunction/javaLangString.go
src/gfunction/justReturn.go

modified:   gfunction/justReturn.go
String is done enough for now.
Won't do: deprecated functions.
Marked as `TODO`:
* Functions referencing charset
* Functions referencing codepoints
* Functions referencing locales
* String.describeConstable()
* String.indent()
* String.join(.....)
* String.lines()
* String.resolveConstantDesc()
* String.splitWithDelimiters()
* String.stripIndent()
* String.translateEscapes()

JACOBIN-555 finished except for some TODOs

---

src/gfunction/javaLangString_test.go

* The Klass field of object.Object is required by function `object.ByteArrayFromStringObject`.
*  In `TestLastIndexOfCharacter` and `TestLastIndexOfString`, keep in mind that the search is right-to-left, not left-to-right.

JACOBIN-555 fix string tests

---

src/jvm/run.go
src/shutdown/exit.go
src/statics/statics_test.go

modified:   jvm/run.go
modified:   shutdown/exit.go
modified:   statics/statics_test.go  (fixed a cycle)

JACOBIN-586 ensure that DumpStatics is called for all anomalies

---

src/classloader/classloader.go
src/globals/globals.go
src/trace/trace.go
src/trace/trace_test.go

First commit:
* trace/trace.go (new)
* trace/trace_test.go (new)
* globals/globals.go  <--- only the Trace flags; still need to do the CLI options in concert with jvm/cli.go and jvm/option_table_loader.go
* classloader/classloader.go <--- One-off loading of java/lang/Class during init is unnecessary
The complete list of files to convert i.e. TBD (mostly, log.Log calls to trace.Trace calls conditioned on the new globals.Trace* flags):
1. classloader/archives.go
2. classloader/classes.go
3. classloader/classloader.go
4. classloader/formatCheck.go
5. classloader/jmodBase.go
6. classloader/jmodBytes.go
7. classloader/jmodMap.go
8. classloader/methArea.go
9. classloader/methodParser.go
10. classloader/parser.go
11. exceptions/catchFrame.go
12. exceptions/errors.go
13. exceptions/throw.go
14. …

JACOBIN-498 Incremental PR

---

src/trace/trace.go

modified: trace/trace.go
Two reasons:
* Compatibility with previous severe messages
* jacotest cannot tolerate time-stamps in severe error messages because it throws off comparison to the previous result (false differences)

JACOBIN-498 Make trace.ErrorMsg formatting like log.Log-severe

---

src/gfunction/javaLangDouble.go

In javaLangDouble.go, function Double.compare(doubleA, doubleB)
```
MethodSignatures["java/lang/Double.compare(DD)I"] =
GMeth{
ParamSlots: 4,
GFunction:  doubleCompare,
}
// "java/lang/Double.compare(DD)I" (corrected from current source code!)
func doubleCompare(params []interface{}) interface{} {
dd1 := params[0].(float64)
dd2 := params[2].(float64) // Corrected: 1 --> 2 !
if dd1 == dd2 {
return int64(0)
}
if dd1 < dd2 {
return int64(-1)
}
return int(1)
}
```

Fixed Double bug as documented in recent email

---

src/jvm/jvmStart.go
src/trace/trace.go

1. I forgot to call trace.Init() in jvmStart.go but it makes little difference.
2. I checked the duration calculation by inserting a time.Sleep call for 100 ms in trace.Trace. The calculation is accurate. I subsequently commented out the time.Sleep call.
I don't know why the trace shows insignificant elapsed time. What was the case when we used the log package? I'd guess that the same phenomenon occured.

JACOBIN-498 check trace.Trace duration value

---

src/gfunction/javaLangMath.go
src/jvm/run.go

Modified: 
* jvm/run.go function createAndInitNewFrame, near the end
* gfunction/javaLangMath.go - fix double arguments in addExactJJ, atan2Float64, and copySignDD

JACOBIN-598 need to allocate double-slots for local variables type D and J; JACOBIN-592 fix arguments in various functions

---

src/gfunction/javaUtilHexFormat.go
src/object/object.go

All but this:
* java/lang/CharSequence - bah!
* hashCode()
* java/util/HexFormat.parseHex([CII)[B
Everything works except equals(), not that I think that many folks are really comparing  2 HexFormat objects.
I think the trouble lies with the HEX_FORMAT static object because functions of() and ofDelimiter() needed extra field assignments that should not have been necessary. Hexxed?
@platypusguy  PLEASE review.

JACOBIN-614 vastly improved support for HexFormat but one gerkhin: equals()

---

src/gfunction/javaLangDouble.go
src/gfunction/javaLangStringBuilder.go
src/gfunction/javaUtilHexFormat.go
src/object/object.go
src/object/object_test.go

* Added unit tests for CloneObject.
* Found resolution for HexFormat.equals() issue.
* Removed unnecessary work-arounds in HexFormat.of() and HexFormat.ofDelimiter() code.
* StringBuilder and StringBuffer follow the API.
* The Java library Double.valueOf() functions (2) cannot handle a G-function exception; flow gets lost somewhere. Implemented as G-functions.

JACOBIN-614, JACOBIN-615, and JACOBIN-601 fixes

---

notes/Initialisation.txt
src/classloader/jmodMap.go
src/classloader/jmodMap_test.go
src/classloader/mTable.go
src/gfunction/Traps.go
src/gfunction/gfunction.go
src/gfunction/javaIoFilterInputStream.go
src/jvm/initializerBlock.go
src/jvm/instantiate.go
src/jvm/jvmStart.go

New: 
* notes/Initialisation.txt
* src/gfunction/javaIoFilterInputStream.go (trying to move jacotest case zippy along)
Modified:   
* src/gfunction/Traps.go - removed javaIoFilterInputStream 
* src/gfunction/gfunction.go - added load of method signatures for javaIoFilterInputStream
* src/jvm/jvmStart.go - removed redundant trace.Init call
Minor nonfunctional fixes:
* src/classloader/jmodMap.go
* src/classloader/jmodMap_test.go
* src/classloader/mTable.go
JACOBIN-620 fix: jvm/initializerBlock.go

JACOBIN-619 Initialisation needs a notes file, new: javaIoFilterInputStream

---

src/classloader/mTable.go
src/gfunction/Traps.go
src/gfunction/gfunction.go
src/gfunction/javaIoConsole.go
src/gfunction/javaIoInputStreamReader.go
src/gfunction/javaLangObject.go
src/gfunction/javaLangSystem.go
src/gfunction/otherMethods.go
src/globals/globals.go
src/jvm/interpreter_LL-end_test.go

*  classloader/mTable.go - added a dump MTable function (useful for debugging)
*  gfunction/Traps.go - more traps!
*  gfunction/gfunction.go - added returnCharsetName() from globals FileEncoding for the G-functions
*  gfunction/javaIoConsole.go - minor cleanup
*  gfunction/javaIoInputStreamReader.go - filled out with traps
*  gfunction/javaLangObject.go - filled out with traps
*  gfunction/javaLangSystem.go - get the "native.encoding" from globals FileEncoding
*  gfunction/otherMethods.go - misc changes
*  globals/globals.go - added func GetCharsetName()
*  jvm/interpreter_LL-end_test.go - Traded `java/lang/Object.wait(JI)V` for `java/lang/Double.hashCode()I`. 
More details in JACOBIN-622.

JACOBIN-622 traps cleanups, added traps, jvm/interpreter_LL-end_testgo fun!, global.FileEncoding = name of character set

---

src/exceptions/catchFrame.go
src/gfunction/Traps.go
src/gfunction/otherMethods.go
src/jvm/interpreter.go

- src/exceptions/catchFrame.go:locateExceptionFrame - If servicing a G-function exception, simply indicate that there are no exception handlers.
- src/gfunction/Traps.go - inconsequential
- src/gfunction/otherMethods.go - inconsequential
- src/jvm/interpreter.go[GETFIELD] - doGetfield() should avoid a go runtime exception due to a nil pointer. Include class and field name in error message.
- src/jvm/interpreter.go[PUTSTATIC] - add class names in field diagnostics for doPutStatic()

JACOBIN-623 locateExceptionFrame: Treat G-functions like a simple exception w/o a catch

---

src/gfunction/jj.go
src/globals/globals.go
src/jvm/run.go
src/object/format.go
src/object/format_test.go
src/shutdown/exit.go
src/statics/statics.go
src/statics/statics_test.go

* gfunction/jj.go - jjDumpStatics(), jjDumpObject()
* globals/globals.go - sort string slice case-insensitive
* jvm/run.go - use new DumpStatics()
* object/format.go - new DumpObject()
* object/format_test.go[TestDumpObjectFieldTable] - avoid static definitions, use new DumpObject()
* shutdown/exit.go - use new DumpStatics()
* statics/statics.go - new DumpStatics()
* statics/statics_test.go - test new DumpStatics()

JACOBIN-626 : new DumpStatics and DumpObject

---

src/gfunction/jj_test.go
src/object/format.go

That was a formatting bug in `object/format.go` function `fmtHelper`.

JACOBIN-626 fix for DumpObject where a field is static

---

src/classloader/parser.go
src/gfunction/jj.go
src/jvm/instantiate.go
src/statics/statics.go

modified:   classloader/parser.go
modified:   jvm/instantiate.go
- In parser.go parseFields(): If the field is static, add it to the statics table.
- In instantiate.go InstantiateClass(): If the field is not yet in the statics table, add it with current dummy values; else leave the existing statics table entry alone.
@platypusguy 
I do not yet have a solution for static String variables, other arrays ([), and  references (L) BUT the I, J, F, D, S, and Z cases seem to be solved.

JACOBIN-604 verified partial solution

---

src/gfunction/javaIoFileInputStream.go
src/gfunction/javaIoFileOutputStream.go
src/gfunction/javaIoOutputStreamWriter.go
src/gfunction/javaLangString.go
src/object/arrays.go

Source files impacted:
* JACOBIN-630  object/arrays.go MakeArrayFromRawArray missed the array of objects case.
* JACOBIN-630  gfunction/javaLangString.go, `MethodSignatures["java/lang/String.replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;"]` was vectored to the wrong function (`stringReplaceCC`). This should have referenced `stringReplaceAllRegex`.
jacotest cases that moved on to "Native method requested: java/lang/Class.isArray()Z":
- array-list-iterator
- playfair
- sieve
- vector-survivor-2
Fixed the JACOBIN-613 gfunction/javaIo*.go files for the file I/O jacotest cases:
* io_fileinputstream
* io_fileoutputstream
* io_filewriter
* io_outputstreamwriter

JACOBIN-630, JACOBIN-613 (io)

---

src/classloader/cpUtils.go

See new entries in JACOBIN-605.
modified:   classloader/cpUtils.go

JACOBIN-605 trace.Error before returning nil class

---

src/exceptions/throw.go
src/frames/frames.go
src/gfunction/gfunctionExec.go
src/jvm/interpreter.go
src/native/nativeFuncExec.go

frames.FormatFQN:
```
// From the given frame, return the FQN as a formatted string.
func FormatFQN(fr *Frame) string {
return fmt.Sprintf("%s.%s%s", util.ConvertInternalClassNameToUserFormat(fr.ClName), fr.MethName, fr.MethType)
}
```
throw.go: amended to use ```FormatFQN``` consistently.
interpreter.go: amended to rely on ```ThrowEx``` to supply FQN information.
Also, remove redundant FQN announcement in:
* gfunction/gfunctionExec.go
* native/nativeFuncExec.go
NOTE: run.go ```runThread``` untrapped panic handling has not yet been addressed.

JACOBIN-645 throw.go, frames.go, interpreter.go

---

src/gfunction/javaIoPrintStream.go
src/globals/globals.go

modified:   globals/globals.go (superfluous comments removed)

jACOBIN-646 fix javaIoPrintStream.go 2 if-statements

---

src/gfunction/javaIoConsole.go
src/gfunction/javaIoFile.go
src/gfunction/javaIoFileInputStream.go
src/gfunction/javaIoFileOutputStream.go
src/gfunction/javaIoFileReader.go
src/gfunction/javaIoFilterInputStream.go
src/gfunction/javaIoInputStreamReader.go
src/gfunction/javaIoOutputStreamWriter.go
src/gfunction/javaIoPrintStream.go
src/gfunction/javaIoRandomAccessFile.go
src/gfunction/javaLangByte.go
src/gfunction/javaLangClass.go
src/gfunction/javaLangDouble.go
src/gfunction/javaLangInteger.go
src/gfunction/javaLangLong.go
src/gfunction/javaLangMath.go
src/gfunction/javaLangString.go
src/gfunction/javaLangStringBuffer.go
src/gfunction/javaLangStringBuilder.go
src/gfunction/javaLangSystem.go
src/gfunction/javaLangThread.go
src/gfunction/javaMathBigInteger.go
src/gfunction/javaSecuritySecureRandom.go
src/gfunction/javaUtilArrays.go
src/gfunction/javaUtilArrays_test.go
src/gfunction/javaUtilHexFormat.go
src/gfunction/javaUtilRandom.go
src/gfunction/jdkInternalMiscUnsafe.go

JACOBIN-649 modified: javaIoPrintStream.go (Object and String consolidations)
JACOBIN-538  error message clean up (mostly, add prefix = name of function where diagnosis occurred):
* javaIoConsole.go
* javaIoFile.go
* javaIoFileInputStream.go
* javaIoFileOutputStream.go
* javaIoFileReader.go
* javaIoFilterInputStream.go
* javaIoFileInputStreamReader.go
* javaIoFileOutputStreamWriter.go
* javaIoRandomAccessFile.go
* javaLangByte.go
* javaLangClass.go
* javaLangDouble.go
* javaLangInteger.go
* javaLangLong.go
* javaLangMath.go
* javaLangString.go
* javaLangStringBuffer.go
* javaLangStringBuilder.go
* javaLangSystem.go
* javaLangThread.go
* javaLangMathBigInteger.go
* javaSecuritySecureRandom.go
* javaUtilArrays.go
* javaUtilArrays_test.go
* javaUtilHexFormat.go
* javaUtilRandom.go
* …

JACOBIN-649 consolidation in javaIoPrintStream.go for Object and String + a bit of JACOBIN-538

---

src/gfunction/gfunctionExec.go

The caller's FQN is important for knowing the context of the call to a G-function.
Upon return to RunGfunction, the FQN of the attempted G-function needs to be added to the error text.
Then, we know which function made the call and which class or function was trapped because of the call.
This is a minor change to gfunctionExec.go RunGfunction.

JACOBIN-654 name the G thing being trapped

---

src/statics/statics.go
src/util/filenameUtils.go

modified:   statics/statics.go - call IsFilePartOfJDK
modified:   util/filenameUtils.go - call ConvertInternalClassNameToUserFormat to normalise class name

JACOBIN-656 IsFilePartOfJDK should call ConvertInternalClassNameToUserFormat

---

src/gfunction/javaSecuritySecureRandom.go
src/gfunction/javaUtilHexFormat.go
src/object/string.go
src/object/toString_test.go
src/types/javaTypes.go

* gfunction/javaSecuritySecureRandom.go:
- fixed bugs
- trap unsupported functions
- added user seed support
* gfunction/javaUtilHexFormat.go: support both []byte and []types.JavaByte.
* object/string.go: amended ObjectFieldToString switch fld.Ftype to accept 
case types.RNG: return "RandomNumberGenerator"
* types/javaTypes.go: added:
- const RNG = "RG"        // RandomNumberGenerator is a Golang *rand.Rand
- func Int64ToBytesBE(arg int64) []byte // Convert an int64 to a byte array in network byte order (BigEndian)
- func BytesToInt64BE(arg []byte) int64 // Convert a byte array in network byte order (BigEndian) to an int64

JACOBIN-660 SecureRandom and accompaniments

---

src/object/string.go
src/object/string_test.go

modified:   object/string.go
modified:   object/string_test.go
When ObjectFieldToString cannot determine field type, return:
`fmt.Sprintf("UNRECOGNISED: %s.%s(Ftype: %s)", GoStringFromStringPoolIndex(obj.KlassName), fieldName, fld.Ftype)`

JACOBIN-667 return the class name, field name, and the field type with a prefix when the field type is unrecognised

---

src/gfunction/javaLangBoolean.go
src/gfunction/javaLangString.go
src/object/string.go

- 668 modified: javaLangBoolean.go - filled out. Note that quite a few of the JVM library routines intermingle just fine.
- 643 modified:   gfunction/javaLangString.go - valueOfObject() is using field "name" if field "value" is not present.
- 643 modified:   object/string.go - ObjectFieldToString() is allowing "LjavaLangString;" as a field name.

JACOBIN-668 Fill out class Boolean in the gfunction package

---

src/gfunction/Traps.go
src/gfunction/gfunction.go
src/gfunction/javaLangRuntime.go
src/gfunction/otherMethods.go

* new file:   gfunction/javaLangRuntime.go - 
--- `<clinit>`, getRuntime(), and availableProcessors(). 
--- Trap all other methods.
* modified:   gfunction/gfunction.go - call Load_Lang_Runtime().
* modified:   gfunction/Traps.go - stop trapping `<clinit>` for java/io/ByteArrayInputStream.
* modified:   gfunction/otherMethods.go - small `<clinit>` for java/io/ByteArrayInputStream.

JACOBIN-666 - mostly, a modest javaLangRuntime.go

---

src/statics/statics.go

It used to be:
```if flagTraceStatics && util.IsFilePartOfJDK(&name)```
i.e. without a '!' infront of ```util.IsFilePartOfJDK(&name)```

statics.go line 66: if flagTraceStatics && !util.IsFilePartOfJDK(&name)

---

.github/workflows/go.yml
src/gfunction/gfunction.go
src/gfunction/javaIoConsole.go
src/gfunction/javaLangByte.go
src/gfunction/javaLangCharacter.go
src/gfunction/javaLangInteger.go
src/gfunction/javaLangLong.go
src/gfunction/javaLangShort.go
src/gfunction/javaLangString.go
src/gfunction/javaMathBigInteger.go
src/object/arrays.go
src/object/string.go
src/testutil/testUtil.go
src/testutil/testUtil_test.go

JACOBIN-674:
* testutil/testUtil.go, testutil/testUtil_test.go: new unit test utilities and self-tests.
JACOBIN-675:
* object/string.go: new function: GoStringFromJavaCharArray().
* gfunction/javaLangString.go: fix toCharArray(), field type should be types.CharArray, not types.IntArray.
* gfunction/gfunction.go: new home to Populator() and InitBigIntegerField(). 
* The other source files were impacted only by capitalisations.
JACOBIN-676:
* object/arrays.go ArrayLength(): treat types.CharArray the same as types.IntArray.

JACOBIN-674, JACOBIN-675, JACOBIN-676

---

src/jvm/runUtils_test.go
src/testutil/testUtil.go

* testutil/testUtil.go UTnewConsole() - amended to close read-side pipe immediately after opening it.
* jvm/runUtils_test.go - TestPushPeekPop() and TestEmitTraceData() amended to use UTnewConsole() & UTrestoreConsole().

JACOBIN-682 Fix to Windows pipe build up

---

src/gfunction/jj.go
src/gfunction/jj_test.go
src/globals/globals.go
src/jvm/runUtils.go
src/jvm/runUtils_test.go
src/object/format.go
src/object/format_test.go
src/object/string.go
src/statics/statics.go

gfunction
* jj_test.go - TestJjStringifyScalar_RefNonNull: InitGlobals("test").
jvm
* runUtils.go - JACOBIN-683 getSuperclasses() failed to diagnose nil return from MethAreaFetch.
* runUtils_test.go - JACOBIN-680 expanded coverage for runUtils.go to 80%.
object
* format.go - handle JavaByte arrays better.
* format_test.go 
- JACOBIN-687 TestFmtHelper(). Expanded coverage to 75%.
- JACOBIN-684 avoid GetStaticValue crash by setting up globals.FuncThrowException.
* string.go - new func: StringPoolIndexFromGoString.
statics
* statics.go - correct comments.

JACOBIN-680, 683, 684, 686, 687

---

src/gfunction/gfunction.go
src/gfunction/javaLangBoolean.go
src/gfunction/javaLangSecurityManager.go
src/gfunction/javaLangSystem.go
src/gfunction/javaUtilHashMap.go
src/gfunction/javaUtilHashSet.go
src/gfunction/javaUtilProperties.go
src/go.mod
src/go.sum
src/types/javaTypes.go
src/util/hashing.go
src/util/hashing_test.go

JACOBIN-698
- modified: gfunction/javaUtilProperties.go - Add some additional evidence when things go astray.
- modified: types/javaTypes.go - Properties constructs.
JACOBIN-699
- new: gfunction/javaLangSecurityManager.go - a NOP, TODO: remove it and references in javaLangSystem.go and gfunction.go in the future when Java stops using it (deprecated but still in use).
- modified: gfunction/javaLangSystem.go - do not return nil for getSecurityManager().
JACOBIN-702
- new: gfunction/javaUtilHashSet.go - used HashMap for storage; key is a hash of the argument to HashSet.add.
- new: util/hashing.go - HashAnything().
- new: util/hashing_test.go - unit tests for HashAnything().
- modified: go.mod, and go.sum - incorporating github.com/cespare/xxhash/v2 in support of HashAnything().
Modified: …

JACOBIN-698 (Properties), JACOBIN-699 (NOP SystemManager)

---

.github/workflows/run_platypusguy_jacobin.yml

On demand, `workflows/run_platypusguy_jacobin.yml` will run jacotest against https://github.com/platypusguy/jacobin.
Testing jobs:
* jacotest -x (does not abort)
* jacotest -r 3

new workflow, on demand, jacotest/jacobin

---

src/gfunction/gfunction.go
src/gfunction/javaLangRuntime.go
src/gfunction/javaLangString.go
src/gfunction/javaLangString_test.go
src/gfunction/javaLangSystem.go
src/gfunction/javaLangSystem_test.go
src/gfunction/javaLangThrowable.go
src/gfunction/javaMathBigInteger.go
src/gfunction/javaSecuritySecureRandom.go
src/gfunction/javaUtilConcurrentAtomicAtomicInteger.go

modified:   gfunction/javaLangRuntime.go
modified:   gfunction/javaLangString_test.go
modified:   gfunction/javaLangSystem.go
modified:   gfunction/javaLangSystem_test.go
modified:   gfunction/javaLangThrowable.go
modified:   gfunction/javaMathBigInteger.go
modified:   gfunction/javaSecuritySecureRandom.go
modified:   gfunction/javaUtilConcurrentAtomicAtomicInteger.go

JACOBIN-705 <clinit> and <init> functions must always return nil

---

src/gfunction/javaIoPrintStream.go
src/go.mod

Kalman filtering output
Hotspot
```
Exercise Kalman filtering
initializePLL: cosine: 0.9829930567854869, sine: 0.1836427246354304
initializePLL: modelVariance: 0.5, noiseAmplitude: 1000000.0, initialStateVariance: 10000.0
initializePLL: Initialised Kalman Filter matrices : {F=32[0.982993, 0.183643; -0.183643, 0.982993], Q=32[0.500000, 0.000000; 0.000000, 0.500000], H=16[1.000000, 0.000000], R=8[1000000000000.000000], P=32[10000.000000, 0.000000; 0.000000, 10000.000000], x=16[0.000000; 0.000000]}
testPhaseLockedLoop: mSteps: 20000
testPhaseLockedLoop: residual array (1st 3): -7.070098417349415 -1.8353661230849327 -3.607469944173245
Residual mean: 0.0033659341574785707, variance: 0.002495718144944807
abs(mean) < 0.5 : true
abs(variance) < 0.5 : …
```

JACOBIN-707 fix printing of float64 to be more like hotspot

---

src/jvm/interpreter.go
src/jvm/interpreter_LL-end_test.go

The POP2 code was popping off 2 items. Jacobin only should have 1 popped off because we never push more than one item.
This was not seen before because of the G function cover-up in returning something in cases when we should have been returning nil, namely `<clinit>` and `<init>`.

JACOBIN-710 fix POP2

---

src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangDouble.go
src/gfunction/javaUtilHashSet.go
src/jvm/initializerBlock.go
src/jvm/interpreter.go
src/jvm/run.go
src/jvm/runUtils.go

A few places missed showing the MethodType while displaying the FQN:
* src/jvm/initializerBlock.go
* src/jvm/run.go
* src/jvm/runUtils.go
Also, modified src/jvm/interpret.go LDC such that when it is diagnosing the CPe.EntryType, show the invalid value.
JACOBIN-714 fixed gfunction/javaUtilHashSet.go to hash only the field value.
JACOBIN-713 fixed gfunction/javaLangDouble.doubleToLongBits to return an int64 instead of an int.

a few places missed showing the MethodType

---

src/gfunction/gfunction.go
src/gfunction/javaLangCharacter.go
src/gfunction/javaLangDouble.go
src/gfunction/javaLangFloat.go
src/gfunction/javaLangProcessHandleImpl.go

JACOBIN-500 move from native function requested to `java.lang.NullPointerException: FQN: main.main([Ljava/lang/String;)V, INVOKEINTERFACE: object whose method, java/lang/ProcessHandleinfo()Ljava/lang/ProcessHandle$Info;, is invoked is null`
* gfunction/javaLangProcessHandleImpl.go
* modified:   gfunction/gfunction.go
Cleanup some return values:
*   gfunction/javaLangCharacter.go
*   gfunction/javaLangDouble.go
*   gfunction/javaLangFloat.go

JACOBIN-500 INVOKEINTERFACE move from native function requested to other things

---

src/gfunction/javaIoPrintStream.go
src/jvm/interpreter.go
src/jvm/interpreter_II-LD_test.go

modified:   gfunction/javaIoPrintStream.go - fix when an printing an object that has no fields.
modified:   jvm/interpreter.go - doIshr and doIushr.
modified:   jvm/interpreter_II-LD_test.go - Fixed doIushr test but we need more Jacotest cases and unit tests for shifting, in general.

JACOBIN-717 Fixed doIshr and doIushr

---

src/gfunction/gfunction.go
src/gfunction/javaLangClass.go
src/gfunction/javaLangObject.go
src/gfunction/jdkInternalMiscUnsafe.go
src/gfunction/otherMethods.go

modified:   gfunction/gfunction.go : added returnRandomLong()
modified:   gfunction/jdkInternalMiscUnsafe.go : added getLong()
modified:   gfunction/javaLangObject.go: added equals().
modified:   gfunction/javaLangClass.go: sorted MethodSignature entries by FQN (no functional changes).
modified:   gfunction/otherMethods.go : added
* jdk/internal/misc/VM.initialize()V - justReturn
* jdk/internal/misc/CDS.getRandomSeedForDumping()J - returnRandomLong
* jdk/internal/misc/CDS.isDumpingClassList0()Z - returnFalse

JACOBIN-719 implement Unsafe.getLong

---

src/gfunction/gfunction.go
src/gfunction/javaIoPrintStream.go
src/gfunction/javaLangObject.go
src/gfunction/javaLangString.go
src/gfunction/javaMathBigInteger.go
src/gfunction/javaUtilLinkedList.go
src/gfunction/javaUtilLinkedListFuncRtoZ.go
src/object/object.go
src/object/string.go
src/object/stringifyAnything.go
src/types/javaTypes.go

‎src/gfunction/javaMathBigInteger.go - `<init>`: remove hotspot library fields Jacobin does not use.
src/gfunction/javaIoPrintStream.go - print(object) corrections.
src/object/stringifyAnything.go - field type corrections, especially handling hotspot-generated field types.
‎src/gfunction/javaLangString.go - correct String field type.
‎src/object/string.go - correct String field type.
src/object/object.go - correct String field type.

JACOBIN-727 Improve object and LinkedList printing again

---

src/gfunction/gfunction.go
src/gfunction/javaMathBigDecimal.go
src/gfunction/javaMathBigDecimalClinitInitHelpers.go
src/gfunction/javaMathBigDecimalFuncAtoM.go
src/gfunction/javaMathBigDecimalFuncNtoZ.go
src/gfunction/javaMathBigInteger.go
src/types/javaTypes.go

new file:   gfunction/javaMathBigDecimal.go - just the MethodSignatures load table entries.
new file:   gfunction/javaMathBigDecimalClinitInitHelpers.go - `<init>` and helper functions.
new file:   gfunction/javaMathBigDecimalFuncAtoM.go - Functions whose name begin with A to M.
new file:   gfunction/javaMathBigDecimalFuncNtoZ.go - Functions whose name begin with N to Z.
modified:   gfunction/gfunction.go - load the BigDecimal MethodSignatures entries.
modified:   gfunction/javaMathBigInteger.go - minor fixes.
modified:   types/javaTypes.go - types.BigDecimal.
This is essentially a BigDecimal only PR.
@platypusguy  See https://jacobin.myjetbrains.com/youtrack/issue/JACOBIN-729/Fill-out-BigDecimal

JACOBIN729 BigDecimal

---

notes/javaBaseShare-natives-byParam.md
src/gfunction/javaLangInteger.go
src/gfunction/javaLangRuntime.go
src/gfunction/javaLangSystem.go
src/gfunction/javaLangSystem_test.go
src/globals/globals.go

- src/gfunction/javaLangSystem.go - move system property functions to global; added more functions and traps.
- src/globals/globals.go - new functions to support system properties, independent of O/S.
- src/gfunction/javaLangSystem_test.go - added globals.InitGlobals("test") in all unit tests that did not previously call this function; updated tests to use global functions; added new unit tests for new functions.
- src/gfunction/javaLangInteger.go - globals.GetSystemProperty(name).
- src/gfunction/javaLangRuntime.go - reflects a function name change, exitI to systemExitI,
- notes/javaBaseShare-natives-byParam.md - reflects a function name change, currentTimeMillis to systemCurrentTimeMillis.
So, now, Java programs can set properties, remove properties, and replace all of them from a …

JACOBIN-730 java/lang/System expansion

---

src/gfunction/Traps.go
src/gfunction/javaLangClass.go
src/gfunction/javaLangSecurityManager.go
src/gfunction/javaLangStringBuilder.go
src/gfunction/javaLangSystem.go
src/gfunction/javaUtilArrays.go
src/gfunction/otherMethods.go

- modified:   gfunction/Traps.go - move SecurityManager traps to gfunction/javaLangSecurityManager.go.
- modified:   gfunction/javaLangClass.go - trap getComponent().
- modified:   gfunction/javaLangSecurityManager.go - 
- void functions (nearly all of them) --> justReturn.
- non-void returns --> trapDeprecated.
- modified:   gfunction/javaLangStringBuilder.go - append() use object.StringifyAnythingGo.
- modified:   gfunction/javaLangSystem.go - get a dummy SecurityManager.
- modified:   gfunction/otherMethods.go - add java/lang/ThreadLocal.`<clinit>` and `<init>` --> justReturn.
- modified:   gfunction/javaUtilArrays.go - trap copyOf([Ljava/lang/Object;ILjava/lang/Class;)[Ljava/lang/Object;

JACOBIN-731 Re-instate SecurityManager; trap Class.getComponent()

---

src/gfunction/galt.go
src/gfunction/gfunction.go
src/globals/globals.go
src/jvm/interpreter.go
src/jvm/option_table_loader.go

new file:   gfunction/galt.go : See JACOBIN-734 for description.
modified:   gfunction/gfunction.go : if-else logic of loading MethodSignatures familes, based on globals.galt.
modified:   globals/globals.go : globals.galt : If true, load only the MethodSingatures entries from gfunction/galt.go.
modified:   jvm/interpreter.go : fix to ISHR processing when the parameter is a byte or types.JavaByte.
modified:   jvm/option_table_loader.go : implement the -JJ option.

JACOBIN-734 G-alternative mode

---

src/jvm/cli.go
src/jvm/cli_test.go
src/wholeClassTests/Hello1_test.go
src/wholeClassTests/LDIVexception_test.go

modified:   jvm/cli.go
modified:   jvm/cli_test.go
modified:   wholeClassTests/Hello1_test.go
modified:   wholeClassTests/LDIVexception_test.go

JACOBIN-734 use colon as option key/value separator

---

src/classloader/codeCheck.go
src/jvm/instantiate.go
src/jvm/interpreter.go

src/classloader/codeCheck.go - use the interpreter.go phrase "Empty code segment" to assist Jacotest error categorization.
src/jvm/instantiate.go - show the method descriptor/type when reporting errors.

Minor updates to improve error reporting

---

src/jvm/interpreter.go

interpreter.go - just fix the if-statement causing a panic. See line 1997.
There is a question pending to @platypusguy in issue JACOBIN-737.

JACOBIN-737: fix if statement that causes panic

---

src/jvm/interpreter.go

After exceptions.ThrowEx(excNames.IllegalArgumentException, errMsg, fr) indicates a caught exception, the interpreter should execute a return exceptions.RESUME_HERE.
E.g. func doGetfield just continues after a caught exception, running into other trouble that masks the original issue.
In many interpreter cases, whatever manipulation of the exception frame is performed after the catch, there won't be an effect after return to the main line. This is because the main line will execute the caught frame (selected during ThrowEx) as opposed to the frame in which the exception occurred. However, just to be safe from future code modifications and for the sake of clarity of purpose, it seems better to immediately return and let the interpreter main line execute the caught frame immediately.

JACOBIN-738 interpreter needs to return exceptions.RESUME_HERE when the exception is caught

---

src/classloader/classloader.go
src/gfunction/javaLangProcess.go
src/gfunction/javaLangRuntime.go
src/gfunction/javaLangSystem.go
src/gfunction/javaLangSystem_test.go

JACOBIN-747: _Remove left over line_ <--------- replaced with source file classloader.go from @platypusguy 
JACOBIN-746:
* Add traps to javaLangProcess.go (new)
* Add traps to javaLangRuntime.go
* Show relevant string info in a systemArrayCopy error message

JACOBIN-746 Process (traps), Runtime (traps), and System (errMsg enhancement in systemArrayCopy)

---

src/gfunction/javaLangSystem.go

modified:   gfunction/javaLangSystem.go
It could still use some more work according to 
https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/System.html#arraycopy(java.lang.Object,int,java.lang.Object,int,int)
TODO: Diagnose parameters according to spec.

JACOBIN-753 fix arrayCopy cases

---

src/jvm/interpreter.go
src/object/arrays.go

modified:   jvm/interpreter.go - doIastore
modified:   object/arrays.go - ArrayType

JACOBIN-758 doIastore and ArrayType fail to allow J/C/S types

---

src/gfunction/javaUtilArrays.go

modified:   gfunction/javaUtilArrays.go, func copyOfObjectPointers
See JACOBIN-761 for description.

JACOBIN-761 arrays.copyOf(obj-array, count) created a field type of [LLjava/lang/Object;

---

src/gfunction/javaIoFile.go
src/gfunction/javaUtilRandom.go

modified: gfunction/javaUtilRandom.go - fix routines returning random integers
modified: gfunction/javaIoFile.go 
- added function `File.getName` for an OpenJDK JVM caller; had hoped this would fix an issue.
- found a few places where "byte" was used instead of "JavaByte".

JACOBIN-765 random integer values should be limited to 32 bits

---

src/gfunction/javaIoBufferedReader.go
src/gfunction/javaIoFile.go
src/gfunction/javaIoFileInputStream.go
src/gfunction/javaIoFileOutputStream.go
src/gfunction/javaIoFileOutputStream_test.go
src/gfunction/javaIoFileReader.go
src/gfunction/javaIoFilterInputStream.go
src/gfunction/javaIoRandomAccessFile.go

modified:   gfunction/javaIoBufferedReader.go
modified:   gfunction/javaIoFile.go
modified:   gfunction/javaIoFileInputStream.go
modified:   gfunction/javaIoFileOutputStream.go
modified:   gfunction/javaIoFileOutputStream_test.go
modified:   gfunction/javaIoFileReader.go
modified:   gfunction/javaIoFilterInputStream.go
modified:   gfunction/javaIoRandomAccessFile.go

JACOBIN-766 File G-functions need to use []JavaByte ([]int8) instead of []uint8 for storing String bytes

---

src/gfunction/javaIoBufferedReader_test.go
src/gfunction/javaIoFileInputStream_test.go
src/gfunction/javaIoFile_test.go
src/gfunction/javaIoPrintStream.go
src/gfunction/javaIoPrintStream_test.go
src/gfunction/javaIoRandomAccessFile_test.go
src/jvm/cli.go

New unit tests:
* gfunction/javaIoFileInputStream_test.go
* gfunction/javaIoFile_test.go
* gfunction/javaIoPrintStream_test.go
* gfunction/javaIoRandomAccessFile_test.go
Modified:
* gfunction/javaIoPrintStream.go - refactored to refer to file handles as `io.Writer` so that the unit tests could employ a `bytes.Buffer` for capture.
* jvm/cli.go - add a brief mention of `-jj:galt` in the `-h` option execution.

JACOBIN-726 Expand unit test coverage contributions in package gfunction

---

src/gfunction/javaMathBigDecimalFuncAtoM_test.go
src/gfunction/javaMathBigDecimalFuncNtoZ.go
src/gfunction/javaMathBigDecimalFuncNtoZ_test.go
src/gfunction/javaMathBigDecimalHelpers.go

new file:   gfunction/javaMathBigDecimalFuncAtoM_test.go - new unit tests.
new file:   gfunction/javaMathBigDecimalFuncNtoZ_test.go - new unit tests.
renamed:    gfunction/javaMathBigDecimalClinitInitHelpers.go -> gfunction/javaMathBigDecimalHelpers.go
modified:   gfunction/javaMathBigDecimalFuncNtoZ.go 
* Bug fixes to bigdecimalStripTrailingZeros.
* Added/modified descriptive comments.
modified:   gfunction/javaMathBigDecimalHelpers.go
* Bug fixes to bigdecimalInitString.
* Added function javaLikeRemainder because Go mod & Java mod disagree about the resulting sign! This fixed bigdecimalRemainder.

JACOBIN-726 Implement unit testing for BigDecimal

---

notes/coverage_by_function.txt
src/gfunction/gfunction_test.go
src/gfunction/javaLangDouble_test.go
src/gfunction/javaLangFloat_test.go
src/gfunction/javaLangInteger_test.go
src/gfunction/javaLangLong_test.go
src/gfunction/javaLangMath_test.go
src/gfunction/javaLangString_test.go
src/gfunction/stringFormatter.go
src/gfunction/stringFormatter_test.go

Hip-hip-hooray! Thanks to Junie, %x formats to hex digits when an integer or byte is negative, just like the OpenJDK JVM. 
- modified:   gfunction/stringFormatter.go
- modified:   gfunction/stringFormatter_test.go
Bonus: JACOBIN-726 (expand unit testing)
- modified:   gfunction/gfunction_test.go (added unit tests)
- new file:   gfunction/javaLangDouble_test.go
- new file:   gfunction/javaLangFloat_test.go
- modified:   gfunction/javaLangInteger_test.go (added unit tests)
- new file:   gfunction/javaLangLong_test.go
- new file:   gfunction/javaLangMath_test.go
- modified:   gfunction/javaLangString_test.go (added unit tests)

JACOBIN-435 Conform to Java in formatting with %x

---

src/gfunction/Traps_test.go
src/gfunction/gfunctionExec_test.go
src/gfunction/javaAwtGraphicsEnvironment_test.go
src/gfunction/javaIoConsole.go
src/gfunction/javaIoConsole_test.go
src/gfunction/javaLangBoolean_test.go
src/gfunction/javaLangByte_test.go
src/gfunction/javaLangCharacter_test.go
src/gfunction/javaLangReflectField_test.go
src/gfunction/javaLangString.go
src/gfunction/javaLangSystem.go
src/gfunction/javaMathBigInteger.go
src/gfunction/testGfunctions.go
src/gfunction/testGfunctions_test.go
src/statics/loadPrimiStatics_test.go
src/trace/trace_test.go
src/types/constants_test.go
src/types/typeUtils_test.go

In the `<clinit>` function, make sure that `klass.Data` is not nil as well as `klass` itself:
* gfunction/javaIoConsole.go
* gfunction/javaLangString.go
* gfunction/javaLangSystem.go
* gfunction/javaMathBigInteger.go
New unit test files:
* gfunction/gfunctionExec_test.go
* gfunction/javaAwtGraphicsEnvironment_test.go
* gfunction/javaIoConsole_test.go
* gfunction/javaLangBoolean_test.go
* gfunction/javaLangByte_test.go
* gfunction/javaLangCharacter_test.go
* gfunction/javaLangReflectField_test.go
* gfunction/Traps_test.go
* gfunction/testGfunctions_test.go
* statics/loadPrimiStatics_test.go
* trace/trace_test.go
* types/constants_test.go
* types/typeUtils_test.go
Return the object pointer (*object.Object), not a pointer to the object pointer:
* gfunction/testGfunctions.go
Not included (all …

JACOBIN-726 more unit tests

---

src/gfunction/stringFormatter.go
src/gfunction/stringFormatterDateTime_test.go
src/gfunction/stringFormatter_test.go

Modified:
- src/gfunction/stringFormatter.go
- src/gfunction/stringFormatter_test.go
New:
- src/gfunction/stringFormatterDateTime_test.go
TODO: 
support for BigInteger and BigDecimal

JACOBIN-465 String.format(), printf improvements

---

src/gfunction/gfunction.go
src/gfunction/javaIoFileInputStream.go
src/gfunction/javaLangString.go
src/gfunction/javaMathBigDecimalFuncAtoM.go
src/gfunction/javaMathBigDecimalFuncNtoZ.go
src/gfunction/javaMathBigDecimalSqrt_test.go
src/gfunction/javaMathBigDecimal_50digits_test.go
src/gfunction/javaTextSimpleDateFormat.go
src/gfunction/javaTextSimpleDateFormat_test.go
src/gfunction/javaUtilDate.go
src/gfunction/javaUtilDate_test.go
src/gfunction/javaUtilTimeZone.go
src/gfunction/javaUtilTimeZone_test.go
src/object/string.go
src/object/string_test.go
src/wholeClassTests/ArrayLength_test.go

Miscellaneous updates:
- object/string.go :: instead of returning `""` when encountering an invalid object, report which class of object was the input. Could be enhanced further if desired.
- object/string_test.go :: make unit test look for new error message prefix.
- wholeClassTests/ArrayLength_test.go :: Junie made a strange choice so I fixed it.
- gfunction/javaIoFileInputStream.go :: "java/io/FileInputStream.readNBytes([BII)I" is a new method function reference to an existing method function (they do the same thing). I must have made 2 commits on the same file before pushing.
- gfunction/javaLangString.go :: give a clearer reason why an input object is invalid. Again, I must have made 2 commits on the same file before pushing.
- gfunction/javaMathBigDecimalFuncAtoM.go :: fixed …

Mostly, JACOBIN-778/779 G functions + unit tests for classes SimpleDateFormat, Date, and TimeZone

---

src/gfunction/javaUtilArrays.go
src/gfunction/javaUtilArrays_test.go
src/gfunction/javaUtilObjects.go
src/jvm/interpreter.go
src/jvm/interpreter_checkcast_test.go
src/jvm/interpreter_instanceof_test.go

new file:   jvm/interpreter_checkcast_test.go - additional unit tests.
new file:   jvm/interpreter_instanceof_test.go - additional unit tests.
modified:   jvm/interpreter.go - minor change to use `types.JavaBoolTrue` and `types.JavaBoolFalse inestead` of 1 and 0.
modified:   jvm/interpreter.go - major overhaul of `doInstanceof` to look more like the successful `doCheckcast`.
modified:   jvm/interpreter_instanceof_test.go - removed TODO; all unit tests function as they are supposed to.
_2025-09-13_
modified: gfunction/javaUtilObjects.go - added "java/util/Objects.equals(Ljava/lang/Object;Ljava/lang/Object;)Z".
modified: gfunction/javaUtilArrays.go - filled out java/util/Arrays with additional functional code and traps.

JACOBIN-784 unit tests for INSTANCEOF and CHECKCAST; fixed INSTANCEOF; JACOBIN-778 more G functions and related unit tests

---

src/gfunction/Traps.go
src/gfunction/javaLangThrowable.go
src/gfunction/javaLangThrowable_test.go
src/jvm/interpreter.go

* jvm/interpreter.go : Fixed ATHROW display for String and default valued `detailMessage`.
* gfunction/Traps.go : 
- Added `java/awt/image/BufferedImage.<clinit>()V`.
- Added `<init>` construction traps for BufferedImage and `java/awt/Image` to Traps.go"
* gfunction/javaLangThrowable.go : Added `<init>` functions for nil argument and String argument.
* gfunction/javaLangThrowable_test.go : Added unit tests for add unit tests for `throwableInitNull` and `throwableInitString`.

JACOBIN-778 & JACOBIN-779 miscellaneous small updates
